### ISSUE TITLE
Proposal to improve throughput and decrease resource waste

### ISSUE THREAD

**Issue by brr53** [nats-io/nats.java#1050]
### Proposed change

The NATS java client is very poor in terms of performance because it uses platform threads and blocks on each operation. 

I see NATS made a Vert.x Java Client and was very excited because Vert.x is reactive and scalable. However, the Vert.x client is actually even worse than the nats.java client because it just creates a threadpool and uses it to wrap around nats.java. This defeats the whole purpose of using Vert.x in the first place. 

My issue got no response https://github.com/nats-io/nats-java-vertx-client/issues/54

Now with Java21 introducing Virtual Threads, I highly suggest making nats.java compatible. Usage of platform threads for it is very wasteful. If Virtual Thread support is made, then we will finally have a Java client capable of utilizing the strength of NATS server. Otherwise, due to the heavy performance loss on the client, it is much more sensible to use a slower framework such as Kafka/Redis due to significantly higher performing clients. 

### Use case

Users of NATS java client face issues due to the client's poor scalability.

**Comment by scottf** [comment]
@zekronium Thank you for the feedback. As you have already surmised, the nats-java-vertx-client is just a thin wrapper. Recently there were changes to make message handling be dispatched on the vertx context so it's better, but again still not vertx. We have already been considering making vertx / netty changes to the java client itself exactly as you have noted, but our timeline for doing this is not yet determined.
