### ISSUE TITLE
Unexpected timeout when requesting subject without handlers

### ISSUE THREAD

**Issue by ajax-kolpakov-p** [nats-io/nats.java#1065]
### Observed behavior

When two requests (subject without handlers) started simultaneously on different threads but the same connection - sometimes only one is cancelled immediately by 503 (CancellationException). Second is cancelled by timeout.

### Expected behavior

Both requests fail immediately by CancellationException.

### Server and client version

Server: reproduced on 2.8.4 and 2.10.9
Client: reproduced on 2.15.3 and 2.17.2

### Host environment

aarch64 with nats cluster running in docker

### Steps to reproduce

```java
public class CancellationErrorExample {
    private static void runFor503(Connection connection) {
        try {
            // Handler for `subject1` does not exist, and we should
            // immediately get 503 (CancellationException with null message).
            connection.requestWithTimeout("subject1", new byte[]{}, Duration.ofSeconds(5)).get();
        } catch (Exception e) {
            System.out.println(Thread.currentThread().getName() + ": " + e.getClass().getSimpleName() + " " + e.getMessage());
        }
    }

    public static void main(String[] args) {
        Options options = new Options.Builder().server("nats://localhost:4222").useTimeoutException().build();

        while (true) {
            try (final Connection connection = Nats.connect(options)) {
                System.out.println();

                Thread t1 = new Thread(null, () -> runFor503(connection), "Thread 1");
                Thread t2 = new Thread(null, () -> runFor503(connection), "Thread 2");

                t1.start();
                t2.start();

                t1.join();
                t2.join();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }
}
```

Typical output:

```
Thread 1: CancellationException null
Thread 2: CancellationException null

Thread 1: CancellationException null
Thread 2: CancellationException null

Thread 1: CancellationException null
Thread 2: ExecutionException java.util.concurrent.TimeoutException: Future cancelled, response not registered in time, check connection status.
```

Seems like this problem is related to `inboxDispatcher` initialization in `NatsConnection.java`. _INBOX subscription is not started properly (by the first thread) when second request is already sent.

There is a comment about race condition. It says that AtomicReference `is probably enough`, but seems like it's not for this case.

**Comment by scottf** [comment]
I would expect both to 503 based on this example code which is probably what you expected. I'll definitely look into this, thank you for the report and code.

**Comment by scottf** [comment]
We have determined the root cause of an issue that reports a similar behavior, so are making progress on this, but not resolution yet.
