### ISSUE TITLE
Add reconnect method

### ISSUE THREAD

**Issue by scottf** [nats-io/nats.java#1085]
## Overview

Client should have a way that allows users to force reconnection process.
This can be useful for refreshing auth or rebalancing clients.

When triggered, client will drop connection to the current server and perform standard reconnection process.
That means that all subscriptions and consumers should be resubscribed and their work resumed after successful reconnect where all reconnect options are respected.

For most clients, that means having a `reconnect` method on the Client/Connection handle.

Connection spec has been updated in #258 

### ADR Issue

https://github.com/nats-io/nats-architecture-and-design/issues/259

**Comment by scottf** [comment]
https://github.com/nats-io/nats.java/pull/1100

**Comment by pkgonan** [comment]
@scottf 
hello.

What if I change the JWT Credential and need to do a reconnect based on that token? I can't put the jwt credential in the reconnect API.

**Comment by scottf** [comment]
You could make a custom AuthHandler that reacts the way you want and is aware of changes. This might even be a good addition to the project, would you be interested in trying to contribute?
