### ISSUE TITLE
When the NATS server is unavailable and the number of reconnection times is set to infinite, memory leakage occurs on the NATS client.

### ISSUE THREAD

**Issue by hjk235456** [nats-io/nats.java#1135]
### Observed behavior

When the number of reconnection times is set to -1 and the server is down, messages are stacked in the queue and will not be consumed.

![1715410907127-c9l](https://github.com/nats-io/nats.java/assets/23261047/a4d50010-4b8c-4bcf-992a-ca28c3c4467b)

optionBuilder
        .connectionName(connectName)
        .connectionTimeout(Duration.ofMillis(2 * CONNECTING_TIMEOUT))
        .reconnectWait(Duration.ofMillis(reconnectWaitTime))
        .maxReconnects(-1)
        .executor(es)
        .servers(servers)
        .userInfo(natsUser, natsPassword);

When the connection fails, the reconnection function is invoked. The _poison message is placed in the outgoing and reconnectOutgoing queues of NatsConnectionWriter.

![1715411296188-qlm](https://github.com/nats-io/nats.java/assets/23261047/9b428f5c-4744-41eb-bbf6-5c2f51cd3c29)

![1715411316195-i5y](https://github.com/nats-io/nats.java/assets/23261047/d83c4efb-3eeb-4f32-9582-08c89e0aecf5)

### Expected behavior

The number of reconnection times is set to -1, and the NATS server is not started. In this case, memory leakage does not occur.

### Server and client version

jnats-2.15.6-htrunk2.jar

### Steps to reproduce

1. Set maxReconnects in the connection parameters to -1.
2. The NATS server is not started.

**Comment by scottf** [comment]
@hjk235456 You said:
> When the number of reconnection times is set to -1 and the server is down, messages are stacked in the queue and will not be consumed.

1. Yes the are kept in the queue based on `maxMessagesInOutgoingQueue` Messages consume memory. Does the memory usage stay up after reconnect? Remember it will take some amount of time to empty the queue.
