### ISSUE TITLE
Duplicate "reconnect" events

### ISSUE THREAD

**Issue by joachimglink** [nats-io/nats.java#1147]
### Observed behavior

Starting with jnats 2.17.7 duplicate "reconnect" events are fired if a consumer reconnects.

### Expected behavior

Only one "reconnect" event for the connection should be fired.

### Server and client version

jnats 2.17.7

### Steps to reproduce

- start NATS
- start application and open connection to NATS and attach a io.nats.client.ConnectionListener to it
- stop NATS server
- restart NATS server
- the registered ConnectionListener will receive 2 "connection reconnected" events in short time (~40ms)

In previous versions (I checked 2.17.1 ... 2.17.6), only one such "connection reconnected" event was fired.

We have custom logic based on the reconnect event and we would prefer to be only informed once per reconnect.

**Comment by scottf** [comment]
@joachimglink I fixed this in #1151

**Comment by scottf** [comment]
Fixed in #1151
