### ISSUE TITLE
Uneven connections rebalance with `forceReconnect`

### ISSUE THREAD

**Issue by ajax-koval-d** [nats-io/nats.java#1184]
### Observed behavior

After nats cluster upgrade, we end up with nats connections distributed unevenly between different nodes. To fix this, we want to use `forceReconnect`.

Problem here is that node resolution in `forceReconnect` is not fair, which becomes quite evident in cluster with two nats server nodes. Nats cluster upgrade leaves all connection hanging on one node, and then after triggering `forceReconnect` on each connection, all connection just reconnect on another node, instead of distributing evenly.

As I understand, reason for this is that currently connected server is guaranteed to be at the end of list in a `NatsServerPool`, meaning, that client will not try to reconnect to the currently connected server.

To fix this I'd propose to shuffle list in `NatsServerPool` inside of `forceReconnect` implementation.

### Expected behavior

After force reconnect all connections are distributed evenly.

### Server and client version

nats-server: v2.10.14
nats.java client: 2.9.1

### Steps to reproduce

1. Run nats cluster with 2 servers
2. Open at least 2 connections to the servers with `ignoreDiscoveredServers=true`
Next, simulating nats server upgrade
4. Turn off server 1
5. Wait at least 5 sec
6. Turn on server 1
7. Wait until server starts
8. Turn off server 2
9. Wait at least 5 sec
10. Turn on server 2
11. Wait until servers starts
At this point all connections will be on server 1
12. Trigger `forceReconnect` on all opened connections

Here's the [test case](https://github.com/ajax-koval-d/nats.java/pull/1) (`testRebalanceWithForceReconnect`) that demonstrates the issue.

**Comment by ajax-koval-d** [comment]
@scottf, Thanks for quick response!

I'd like to clarify a bit my idea: what I want is to call `Collections.shuffle` in a middle of a `forceReconnect`, right before `reconnectImpl`, but without putting current server on the bottom, [like this](https://github.com/ajax-koval-d/nats.java/blob/1f1b82424f49c8d4036269ef0a31ceccba0b8f04/src/main/java/io/nats/client/impl/NatsConnection.java#L339). I don't want to change `NatsServerPool` or `reconnectImpl` logic in any way, so standard behavior of reconnect, when connection, for example, disconnected due to network issues will be kept intact - currently connected server will be last on the list.

I believe in that case there's no need to introduce different option, because it will only affect `forceReconnect` call, and to me it seems strange to opt in for unfair distribution here. But if you feel strong about making a separate option, I can provide new implementation of `ServerPool` and add a new method, `shuffle` here, which will be NOOP in `NatsServerPool`.

In any case, I'd be glad to contribute.

By the way, at first I thought about extending `NatsServerPool` in my project, but unfortunately, `listLock` is private in here, and `getServerList` returns a copy, making it essentially impossible to reuse that class.

**Comment by scottf** [comment]
Ok here is the change to NatsServerPool to make it easier to extend. https://github.com/nats-io/nats.java/pull/1185
