### ISSUE TITLE
Add bulk acking/naking APIs

### ISSUE THREAD

**Issue by matthewadams** [nats-io/nats.java#1199]
### Proposed change

_NB:  I asked this question [in the #general channel of the Slack channel](https://natsio.slack.com/archives/C069GSYFP/p1723238305939919), but didn't seem to get much traction.  The proposed methods are slightly different than in the Slack messages after some more thought._

For those use cases where we don't know at design time which `AckPolicy` we want to use, we'd like for there to be more efficient bulk acking/naking APIs on `FetchConsumer`.  These are intended primarily for ordered pull consumers.  We propose the following new interface methods.

* `default void ackAll() { ackAll(true); }`
* `default void nakAll() { ackAll(false); }`
* `default void ackAll(boolean ack) { ack(-1, ack); }` -- acks all messages in one server round trip, similar to `AckPolicy.All`
* `void ack(int n, boolean ack) { ack(n, ack, false); }` -- acks first n messages (all if n < 0) of the batch in one server round trip
* `void ackThenNak(int n);` -- acks first n messages (all if n < 0) then naks the rest in one server round trip

If it's inappropriate for these methods to be placed on `FetchConsumer`, perhaps a new set of batch APIs could be created on `ConsumerContext` to support batches of `Message`s, like

* `BatchConsumer fetchBatch(int maxMessages);`
* `BatchConsumer fetchBatch(int maxBytes);`
* `BatchConsumer fetchBatch(BatchConsumeOptions opts);`

where `BatchConsumer` might be something like
```
package io.nats.client;

public interface BatchConsumer {
    List<Message> getBatch() throws InterruptedException, JetStreamStatusCheckedException;
    int getBatchSize();
    default void ackAll() { ackAll(true); }
    default void nakAll() { ackAll(false); }
    default void ackAll(boolean ack) { ack(getBatchSize(), ack); } 
    void ack(int n, boolean ack);
    void ackThenNak(int n);
}
```

### Use case

The use case is when it's not known at design time which `AckPolicy` should be used, and the developer doesn't want to ack or nak each `Message` individually.

### Contribution

Interested if our resource availability permits it.

**Comment by scottf** [comment]
@matthewadams 
I think this is akin to auto ack, a feature we specifically did not add to simplification and discourage in general because it's the developers responsibility. You are welcome to post this in the [architecture-and-design](https://github.com/nats-io/nats-architecture-and-design) repo as this would have to be designed and approved for all clients.

**Comment by matthewadams** [comment]
Ok, I was a little unsure about how to create the issue over there, but I did anyway, just referring back to this issue.  See https://github.com/nats-io/nats-architecture-and-design/issues/301
