### ISSUE TITLE
Add full support for new Jetstream API

### ISSUE THREAD

**Issue by MichaelSwartz** [nats-io/nats.java#1228]
### Proposed change

Not all functionality of the new Jetstream API is available here, and it would be great if it were! 

Specifically, built-in support for batch processing, which I think was available in the old Java Jetstream API, and is supported in the Golang API, as demonstrated by this example from https://natsbyexample.com/examples/jetstream/api-migration/go :
```
	cons, _ = stream.CreateOrUpdateConsumer(ctx, jetstream.ConsumerConfig{
		InactiveThreshold: 10 * time.Millisecond,
	})
	fetchResult, _ := cons.Fetch(2, jetstream.FetchMaxWait(100*time.Millisecond))
	for msg := range fetchResult.Messages() {
		fmt.Printf("received %q\n", msg.Subject())
		msg.Ack()
	}
```

I would like to be able to get messages similarly to the above to pass them to a batch processor.

Thanks!

### Use case

Batch processing for greater efficiency

### Contribution

If I could convince my employer to let me do it during work time, yes!

**Comment by scottf** [comment]
Let me know if this is what you are looking for: https://github.com/nats-io/nats.java?tab=readme-ov-file#simplification
