### ISSUE TITLE
[question] Embedded nats for java projects?

### ISSUE THREAD

**Issue by kkocel** [nats-io/nats.java#183]
In other solutions (eg mongo: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo) there are libraries that allow to run embedded version of server in order to write integration tests that check things like serialization, correct setup of subjects etc. So my question is - is there such library available for nats?
It would be a great idea to have such library - now in my tests just need to mock whole java-nats which does not give me any clue whether this logic works :)

**Comment by sasbury** [comment]
The tests use this class - https://github.com/nats-io/java-nats/blob/master/src/test/java/io/nats/client/NatsTestServer.java which hopefully does what you want. It runs a gnatsd - see the env var for setting the path if necessary - and can be set to debug mode, or to take a config file or custom config settings.

There is also https://github.com/nats-io/java-nats/blob/master/src/test/java/io/nats/client/NatsServerProtocolMock.java which is a fake server but performs some of the protocol so we can test raw protocol messages.

**Comment by kkocel** [comment]
Yes, it's a nice wrapper but it requires gnatsd to be installed on host machine. Ideally a hypothetical `library` would download gnatsd and call NatsTestServer.java in order to start it.

**Comment by sasbury** [comment]
I will take a look, but would be open to a PR also :-)

I think if i was doing something that did the pull and everything I might change the API a bit, thoughts there?

**Comment by kkocel** [comment]
Sorry, I didn't follow (maybe because I'm not native english speaker ;) ). How pulling the binaries will affect API?

**Comment by sasbury** [comment]
Sorry, i was asking if there are other API changes that would be useful if I get a chance to do the binary pull code.

**Comment by kkocel** [comment]
My impression is (just by brief glance at the code) that pulling binaries could be just implemented without affecting other parts (maybe only adding `pull` option to NatsTestServer).

**Comment by krraghavan** [comment]
Embedded Mongo is built on top of https://github.com/flapdoodle-oss/de.flapdoodle.embed.process which has all the necessary abstractions including multi-version support (i.e. select the version of the executable you want to run in your test).  Quite a handy framework and I've used it successfully to run integration tests with different versions of mongo.  Might be useful here too.

**Comment by CarloWakefield** [comment]
> The tests use this class - https://github.com/nats-io/java-nats/blob/master/src/test/java/io/nats/client/NatsTestServer.java which hopefully does what you want. It runs a gnatsd - see the env var for setting the path if necessary - and can be set to debug mode, or to take a config file or custom config settings.
> 
> There is also https://github.com/nats-io/java-nats/blob/master/src/test/java/io/nats/client/NatsServerProtocolMock.java which is a fake server but performs some of the protocol so we can test raw protocol messages.

May it be that `NatsTestServer.java` is no longer working?
It still uses the `gnatsd` command, but according to the release notes https://github.com/nats-io/nats-server/releases/tag/v2.0.0 and my current MacOS setup the command is now named `nats-server`.

Is my analysis correct?

**Comment by sasbury** [comment]
I haven't updated the test class yet to the new executable name. But the code will work if you make a copy of the executable with the old name `gnatsd`' or set the environment variable `nats_server_path` to the point at the executable.

**Comment by CarloWakefield** [comment]
One can also use NATS inside a [testcontainer](https://github.com/testcontainers/testcontainers-java).
Here is how NATS Streaming Server can be run inside a testcontainer: https://github.com/testcontainers/testcontainers-java/issues/1733#issuecomment-520593092.

**Comment by sasbury** [comment]
Changed the reference to nats-server in 2.6.1.

**Comment by madansp** [comment]
@kkocel  check this library. I recently created this. It is based on [https://github.com/flapdoodle-oss/de.flapdoodle.embed.process ](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process )

**Comment by kkocel** [comment]
@madansp I that covers my use case :)
