### ISSUE TITLE
[proposal] Spring Cloud Stream integration

### ISSUE THREAD

**Issue by kkocel** [nats-io/nats.java#193]
I've just realised that it would be a great idea to provide integration with Spring Cloud Stream. I think that it would increase nats adoption

**Comment by sasbury** [comment]
I haven't used Spring Cloud enough to know what this would involve. Is it small and should go in the core library, or a bit bigger and something that should make its own project?

**Comment by kkocel** [comment]
I would say it can easily fit as module - since it would be just a simple binder. See Google pubsub - https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-pubsub-stream-binder/src/main/java/org/springframework/cloud/gcp/stream/binder/pubsub

**Comment by sasbury** [comment]
Closing as out of scope for the library, but I am open to linking to an integration from the nats.io page if you or someone else creates one.

**Comment by slamdev** [comment]
@kkocel if you still need this: https://github.com/slamdev/nats-spring-cloud-stream-binder

**Comment by sasbury** [comment]
wish i saw this earlier, we have been working on one as well, it should be out in the next couple weeks. @slamdev and @kkocel, once we have something perhaps you an help me get it in sync with your work.

**Comment by slamdev** [comment]
@sasbury I pushed it only couple hours ago :D 

sure, lets stay in touch and work on this together

**Comment by sasbury** [comment]
We have opened the initial release for spring - https://github.com/nats-io/spring-nats - comments and PRs are more than welcome. @slamdev very similar to your work, but if you see any features you want to add feel free to shoot me a PR or an issue.

I plan to let this set for a week or so and then will do an initial release. It is available on sonatype now.
