### ISSUE TITLE
How the client to process incoming messages in parallel?

### ISSUE THREAD

**Issue by xzzh999** [nats-io/nats.java#238]
Hi~

Like [**this question in go**](https://github.com/nats-io/nats.go/issues/466)

Is it still thread-safe in java?

**Comment by sasbury** [comment]
Reading from a subscription using nextMessage is thread safe. Dispatchers use their own thread to call your callback. If you want to "fan out" the work, i would propose using either a dispatcher or single threaded subscriber loop and a queue that you hook workers up to.

**Comment by xzzh999** [comment]
@sasbury 

Hi, thank you for your reply~

you mean like this?  (as follow comments)
```
...

dspt = conn.createDispatcher((msg) -> {
   
   // TODO:
   // here put the msg to a queue, and pull it from another thread pool,
   // and i can call like "conn.publish(msg.getReplyTo(), resultBytes); inside the  
   // consume thread pool" ,
   // it's thread-safe.

}

dspt.subscribe(subjectName);

...
```

**Comment by sasbury** [comment]
you could create a ConcurrentLinkedQueue (for example) and do an add in the dispatcher code. Then read from that queue in another thread.

Something like this - https://stackoverflow.com/questions/2233561/producer-consumer-work-queues

The library manages some things itself but not how you process the messages.

**Comment by xzzh999** [comment]
@sasbury 
That's awesome! Thank you~
