### ISSUE TITLE
The connection took 2 minutes！

### ISSUE THREAD

**Issue by peng-w** [nats-io/nats.java#248]
Operating System：CentOS6.10 x64（ip:172.0.18.213）
Nats-Server：2.0.0 x64（ip:172.0.18.213、port:default ）
Java-Client jar：jnats-2.5.2.jar
Code：[java]
![image](https://user-images.githubusercontent.com/6479081/60254780-1baf4880-9901-11e9-91eb-2227b7c8f257.png)
Problem：Why the connection took 2 minutes？If i'm using Windows system（ip:172.0.18.68），pretty soon！Can you give me some help？Thank you！
![image](https://user-images.githubusercontent.com/6479081/60254160-ff5edc00-98ff-11e9-97d5-61d143224f29.png)

**Comment by sasbury** [comment]
how long does it take to send a ping between the machines?

can you try the NatsPub sample, from the examples jar and see if it has the same problem.

I wrote a similar example and was able to connect to a machine in oregan in < 2s. Can you try that machine - nats://demo.nats.io:4222 - it is open for people to try out. For a local machine I connect in < 0.2 seconds.

**Comment by peng-w** [comment]
I had found problem: My code working in a virtual environment, time took 2 minutes. 

The virtual environment of CentOS6.10 is KVM, I tried to create a new virtual environment(VirtualBox) to run my code, time took 2 minutes too.

printscreen:
![image](https://user-images.githubusercontent.com/6479081/60311605-907a9500-998a-11e9-8687-4338b0bcb9fe.png)
![image](https://user-images.githubusercontent.com/6479081/60311622-a6885580-998a-11e9-83f7-70071988baea.png)
![image](https://user-images.githubusercontent.com/6479081/60311831-8016ea00-998b-11e9-863c-91e19bee21c0.png)

**Comment by peng-w** [comment]
I'm running NatsPub.java on a virtual environment(virtualbox), the connection took 2 minutes.

**Comment by sasbury** [comment]
i have run with virtual box and don't get anything like 2 minutes. something is definitely weird with the KVM/Native networking if the demo.nats.io connection is faster than the one to the local machine.

Can you run outside the KVM?

Also, just for curiosity. Can you do two connections, and time both, right in a row. Not sure it will matter but i am curious.

I am going to ping some other folks and see if they have any ideas.

**Comment by peng-w** [comment]
If i'm using Windows system（run outside the KVM），pretty soon！

**Comment by derekcollison** [comment]
If you could run a simple telnet from the kvm that is running the java NATS client that would be great. NATS servers, even in TLS mode, can be telnet'd to and the server will return an INFO block on connect. You can try also `telnet demo.nats.io 4222` to test. If that is also taking 2 minutes then it is a network issue between the kvm and other IPs. If that test is quick, meaning you get the INFO block immediately, and the java application still takes 2 minutes it is something in the NATS java client or your application.

Happy to help, this info will help us pinpoint the issue.

**Comment by peng-w** [comment]
have a nice weekend，I will try it at work next week.

**Comment by derekcollison** [comment]
ok keep us posted.

**Comment by peng-w** [comment]
Hello: derekcollison, sasbury. This screen shot shows what i'm doing.

![GIF](https://user-images.githubusercontent.com/6479081/60405438-c74ae800-9be2-11e9-92ae-655c7f5ef9d8.gif)

Expect your reply.

**Comment by derekcollison** [comment]
ok thank you, this will be helpful. Will take a look.

/cc @sasbury

**Comment by sasbury** [comment]
My only theory is that we somehow timeout over and over in a loop and then
get lucky, but I don't think the code does that. When I get back wed I am
planning to write a small raw socket test we can try.

**Comment by peng-w** [comment]
local machine:

[test1: vmware15 + windows10 + jnats2.0]
![vmware-win10-jnats2](https://user-images.githubusercontent.com/6479081/60498331-f64b8180-9ce8-11e9-82f2-4dda18c2ead3.gif)

[test2: vmware15 + centos7 + jnats2.0]
![vmware-centos7-jnats](https://user-images.githubusercontent.com/6479081/60499265-b2597c00-9cea-11e9-8c56-ff6946150a61.gif)

[test3: virtualbox6 + centos6.10 + jnats2.0]
![virtualbox-centos6-jnats2 0 0](https://user-images.githubusercontent.com/6479081/60498787-d10b4300-9ce9-11e9-9be8-bb3011aa26ad.gif)

remote machine:
[test4: kvm4.5.0 + centos6.10 + jnats2.0]
![remote](https://user-images.githubusercontent.com/6479081/60499521-3449a500-9ceb-11e9-9215-c499136f8c72.gif)

Try it in kvm, please!

**Comment by derekcollison** [comment]
Thank you for the detailed information, really appreciate that!

Just to confirm the telnet from the remote machine under kvm to the demo server still connects immediately correct?

**Comment by derekcollison** [comment]
Could you also run a different language client, like here: https://github.com/nats-io/nats.go/tree/master/examples/nats-pub to see if the connection delay still exists.

Also do you know what the firewall configuration for the kvm instance is set to?

**Comment by sitepodmatt** [comment]
Third-party Anti-virus / Network firewall on your Windows host thats acting as the network bridge? I noticed your remote machine demo is the same subnet. Have you tried running it on a local linode/vultr/DO.

**Comment by peng-w** [comment]
hi:derekcollison, same environment, golang run well.
   sitepodmatt, i do that.

remote machine:
[test4: kvm4.5.0 + centos6.10 + jnats2.0]
![go](https://user-images.githubusercontent.com/6479081/60563270-b1c5f180-9d8d-11e9-8b46-92ed7779944b.gif)

**Comment by sasbury** [comment]
i have a couple thoughts - one related to the recent change to an executor for part of the connect, but the other more abstract.

peng-w can you try adding a connection and error handler to your test code. Something like this - where builder is the Options.Builder. I want to see what exceptions, errors and connect events you are getting.

```java
			builder = builder.connectionListener(new ConnectionListener() {
				public void connectionEvent(Connection conn, Events type) {
						logger.info("NATS connection status changed " + type);
				}
			});

			builder = builder.errorListener(new ErrorListener() {
				@Override
				public void slowConsumerDetected(Connection conn, Consumer consumer) {
					logger.info("NATS connection slow consumer detected");
				}

				@Override
				public void exceptionOccurred(Connection conn, Exception exp) {
					logger.info("NATS connection exception occurred", exp);
				}

				@Override
				public void errorOccurred(Connection conn, String error) {
					logger.info("NATS connection error occurred " + error);
				}
			});
```

**Comment by peng-w** [comment]
I'm glad to do this, wait a moment

**Comment by sasbury** [comment]
Ok, i am going to try to send you a special version of the library later today. There is definitely a bug because I don't timeout the connection, but that is minor compared to the total connect time. I am going to put a bunch of debug stuff in the connect path.

I will also try to get kvm going, but i am on a mac, so not sure I can replicate easily here.

**Comment by sasbury** [comment]
Can you try this version of the library and an example (basically like yours with different options)

Run with

```bash
 % java -cp jnats-test-fat.jar:jnats-test-examples.jar io.nats.examples.ConnectTime nats://demo.nats.io:4222 
```

Use the cmd line arg for the server, i tried with demo and get:

```bash
Trying to connect to nats://demo.nats.io:4222.

connect trace: starting connection attempt, 5.000 (s) remaining
connect trace: waiting for reader, 5.000 (s) remaining
connect trace: waiting for writer, 5.000 (s) remaining
connect trace: cleaning pong queue, 5.000 (s) remaining
connect trace: connecting data port, 5.000 (s) remaining
connect trace: reading info, version and upgrading to secure if necessary, 5.000 (s) remaining
connect trace: starting reader, 5.000 (s) remaining
connect trace: starting writer, 5.000 (s) remaining
connect trace: sending connect message, 5.000 (s) remaining
connect trace: sending initial ping, 5.000 (s) remaining
connect trace: starting ping and cleanup timers, 5.000 (s) remaining
connect trace: updating status to connected, 5.000 (s) remaining
Status change nats: connection opened
Status change nats: connection closed
Connect time was 0.1731 seconds
```

I had to zip the two jars for github.

[jnats-test-examples.jar.zip](https://github.com/nats-io/nats.java/files/3356079/jnats-test-examples.jar.zip)
[jnats-test-fat.jar.zip](https://github.com/nats-io/nats.java/files/3356080/jnats-test-fat.jar.zip)

**Comment by peng-w** [comment]
Hello:sasbury. This is the result of the execution.

![image](https://user-images.githubusercontent.com/6479081/60633061-91ed0700-9e3b-11e9-9eca-18b13cf894cf.png)

**Comment by sasbury** [comment]
lol - in my rush to give you a jar I messed up my tracing timer, let me give you a new version, it shouldn't say 5 seconds every time.

**Comment by sasbury** [comment]
Ok, can you try with this jar for the library, same example....

[jnats-test-fat.jar.zip](https://github.com/nats-io/nats.java/files/3357374/jnats-test-fat.jar.zip)

**Comment by peng-w** [comment]
The lastest test

![image](https://user-images.githubusercontent.com/6479081/60636704-23637580-9e4a-11e9-8636-7a2a3501f361.png)

**Comment by sasbury** [comment]
ok, this is super weird, the connect time is 120s but the time in the connect method is < 1s. I will take a look at the library and maybe add some more trace code. I have one last thought, the lock that we use on the connect status could be blocking somehow. I am off for a couple days, but will try to get you a new version of the test jar to try as soon as I can.

**Comment by sasbury** [comment]
When you get a chance, can you try this jar, it prints a few more times. Same examples jar.

[jnats-test-fat.jar.zip](https://github.com/nats-io/nats.java/files/3357991/jnats-test-fat.jar.zip)

**Comment by peng-w** [comment]
Glad to cooperate with you.

![image](https://user-images.githubusercontent.com/6479081/60655542-7fe18780-9e80-11e9-9ed3-6137f40525c8.png)

**Comment by sasbury** [comment]
wow, it really looks like the close is what is taking a long time. Did your program time the close as well as the connect? I will add timing to the close.

**Comment by peng-w** [comment]
![image](https://user-images.githubusercontent.com/6479081/60691508-bcee5e00-9f02-11e9-9347-c96621024183.png)

**Comment by sitepodmatt** [comment]
All the problematic demos run on VMs with 1 core only allocated?

**Comment by sasbury** [comment]
yea, my best guess is that there aren't enough cores, so the read/write threads eat up all the processor (although they really shouldn't eat CPU when there is no traffic). peng-w can you confirm if there is only 1 core and try with 2 if that is the case?

**Comment by peng-w** [comment]
CPU The number of physical：1
CPU The number of core：4
CPU The number of thread：4

![image](https://user-images.githubusercontent.com/6479081/60703600-c1cc0580-9f34-11e9-8f3b-3154bc6d654f.png)

**Comment by peng-w** [comment]
CPU The number of physical：4
CPU The number of core：1
CPU The number of thread：4

![image](https://user-images.githubusercontent.com/6479081/60703832-5b93b280-9f35-11e9-8358-f61818020005.png)

**Comment by sasbury** [comment]
So it is using threads. I may need to try to put some more timing in the tracer, but i literally print the one message before returning to main, which prints the second message but says it took much longer. Very weird. Give me a day or two (it is a holiday and the weekend) but i will put something together.

**Comment by sasbury** [comment]
I added more timing - including the initial object creation. Can you try running again with these totally new jars, i really hope we see something useful....

[jnats-test-examples.jar.zip](https://github.com/nats-io/nats.java/files/3364456/jnats-test-examples.jar.zip)
[jnats-test-fat.jar.zip](https://github.com/nats-io/nats.java/files/3364457/jnats-test-fat.jar.zip)

**Comment by peng-w** [comment]
I am enjoying weekend，i will try it one monday. Thanks your helpful with me.

**Comment by peng-w** [comment]
sasbury: Is this helpful to you?

![image](https://user-images.githubusercontent.com/6479081/60776895-cc1f1700-a161-11e9-9389-d075ab2ca4a5.png)

**Comment by sasbury** [comment]
Ugh, i think i know what it might be, and i am mad for not thinking of this earlier. There is an issue with random numbers on linux, we even mention it on the readme, but i totally forgot - https://github.com/nats-io/nats.java#linux-platform-note - it is possible that this is the problem.

Can you try running with `-Djava.security.egd=file:/dev/./urandom`.

I hope this is, it, but am mad that it took me so long to think of it.

**Comment by peng-w** [comment]
sasbury: Don't be angry, you are right.The problem is random numbers.You've been very helpful!

sasbury, derekcollison, sitepodmatt: Nats is an excellent messaging system, Nats team is an excellent team.I am honored to be a user, Thanks for the help from the nats team, again.

![GIF](https://user-images.githubusercontent.com/6479081/60785220-bbcc6380-a184-11e9-8227-2b7aea1091a5.gif)

**Comment by derekcollison** [comment]
Thank you for being so patient!

**Comment by sasbury** [comment]
LOL thanks peng-w for sticking with it. Hopefully next time i will remember my own note quicker ;-)

Glad things are running well now. Please let us know if you find any other issues.

Ok to close the issue?
