### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [nats-io/nats.java#249]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/nats/SecureSocketChannel.java: Line number => 81: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => src/main/java/org/nats/SecureSocketChannel.java: Line number => 89: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by sasbury** [comment]
is this from the 1.x library? That code has been superseded with a completely new version.

**Comment by sasbury** [comment]
Out of date
