### ISSUE TITLE
Add an API to sign bytes with the creds

### ISSUE THREAD

**Issue by sasbury** [nats-io/nats.java#258]

**Comment by brimworks** [comment]
This can already be done via NKey#sign(byte[]): https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/NKey.java#L754

...and you need to create an NKey if you are implementing the AuthHandler: https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/AuthHandler.java
