### ISSUE TITLE
android client can not connect to a remote gnatsd server

### ISSUE THREAD

**Issue by kzeoprf22** [nats-io/nats.java#264]
Hi I am using nats.java (2.6.0) on an android device. The device is connected to local lan vi wifi. From the remote server I can ping the ip address of the android device. In the remote server I ran a gnatsd server on port  4222 and I used "-a" switch to bind it on the desired address which is in the same lan as the android device. In the androide device I granted permision for the "INTERNET" and I do not know if I have to grant to any other permision type. I am trying to connect to the remote server using the Nats.connect("nats://ip:4222") function and I get an exception "UNABLE to connect to NATS server". I used wiresharck also and I can not see any packet living the android device.
Any hint will be veru helpfull.
Thanks

**Comment by kzeoprf22** [comment]
For everyone has the same problem, you must use the connect function of nats inside a new thread and not the main.

**Comment by sasbury** [comment]
that was the easiest issue i solved all week :-) glad you got it working kzeoprf22! Thanks for posting the solution as well.

**Comment by codenoid** [comment]
my environment exactly same like yours @kzeoprf22 , but can you give me example of thread usage in this library ? 

i try : 

```java
new Thread ( new Runnable() {
    @Override
    public void run() {
    try {
            conn = Nats.connect("nats://10.11.15.75:4222");
    } catch (Exception e) {
            e.printStackTrace();
    }
}
}).start();
```

but no luck
