### ISSUE TITLE
How to select listener?

### ISSUE THREAD

**Issue by peng-w** [nats-io/nats.java#269]
Hello:
  I'm putting in a retry mechanism, and I find that I can use two classes!(I'd like to put offline data in redis and resend it when the network recovers.)
  
  Which is the official recommendation? ConnectionListener or ErrorListener? 

  Thank you very much!

**Comment by sasbury** [comment]
These two listeners are notified for different things, so many applications use both.

Reconnect notifications are sent to the connection listener, so that is likely the place you want for that scenario.

**Comment by peng-w** [comment]
ok, @sasbury Thank you for your timely guidance!.
