### ISSUE TITLE
After thread interrupt, how to catch exception?

### ISSUE THREAD

**Issue by peng-w** [nats-io/nats.java#271]
![image](https://user-images.githubusercontent.com/6479081/64513446-27fd4c00-d31b-11e9-9316-812d2e3c9e2b.png)

The code in the box ends the program. How do you catch and reconnect exceptions?

**Comment by sasbury** [comment]
When you lose the connection it means the NATS connection is closed. You would re-open it and then recreate your streaming connection.

Note, if it is just a transient problem where the nats connection auto-reconnects you shouldn't have to do the full connect on the streaming side.

**Comment by peng-w** [comment]
My understanding is wrong, Thank you @sasbury.
