### ISSUE TITLE
Add ability to publish byte arrays with specified offset and length.

### ISSUE THREAD

**Issue by igoberman** [nats-io/nats.java#272]
The current API only allows to publish 'whole' byte array. It means that caller has to allocate array of the precise length to make publish call. This potentially leads to a lot of GC allocations.

Could you add ability to publish array with offset and length. Something like below:

Existing:
void publish(String subject, byte[] data);
To add:
void publish(String subject, byte[] data, int offset, int length);

**Comment by sasbury** [comment]
Right now there is no way for me to let the caller reuse the bytes, because they are held in an outgoing queue until they hit the wire. I could provide helpers to copy the bytes, but I wonder if that won't be deceiving rather than helpful. What do you think?

**Comment by scottf** [comment]
@igoberman In the latest (currently unreleased) client we have an object called ByteArrayBuilder which is like StringBuilder for byte arrays and uses ByteBuffer under the covers. This object allocates the byte array as you need, is customizable (constructable) with an initial size.

Please have a look at https://github.com/nats-io/nats.java/blob/master/src/main/java/io/nats/client/impl/ByteArrayBuilder.java

**Comment by scottf** [comment]
Closing this as won't fix. See note about ByteArrayBuilder
