### ISSUE TITLE
ConnectionListener shows DISCONNECTED twice

### ISSUE THREAD

**Issue by oliverhausler** [nats-io/nats.java#274]
`.connectionListener((conn, type) -> log.info(name + ": " + type.name()))` logs this:

![image](https://user-images.githubusercontent.com/8090341/65545515-602f8d80-deca-11e9-9e8d-bf50694a36fd.png)

Probably not a big issue, but wanted to let you know.

**Comment by sasbury** [comment]
Any chance you could capture a stack trace just so i can track this down. As you say, not a huge deal but maybe an easy fix.

**Comment by oliverhausler** [comment]
There is no stacktrace. The exception you see comes from the ´errorListener` not the `connectionListener`. On the `connectionListener` I am just seeing the event.

I could get you the stacktrace for the `exceptionOccurred` event, but I don't think it will help much.

**Comment by sasbury** [comment]
sorry, i meant, can you do a `(new Exception()).printStackTrace()` in that callback so we can see where they happen. I can try it on a sample when I get a chance, just figured you might be able to grab it while you are poking around.

**Comment by oliverhausler** [comment]
I don't see much as our k8s environment has just been set up and logging isn't fully configured. Stack traces are not in sequence. Hope it helps.

Only line which I see repeatedly in NATS is this: `at io.nats.client.impl.NatsConnection.lambda$processConnectionEvent$10(NatsConnection.java:1420)`

![image](https://user-images.githubusercontent.com/8090341/65556618-025c6f00-dee5-11e9-9079-c14dbb6db3d1.png)
