### ISSUE TITLE
Authentication via username/password?

### ISSUE THREAD

**Issue by stodge** [nats-io/nats.java#278]
Sorry for the silly question, but does the nats.io Java API support authentication via a username and password pair? The documentation implies that the nats.io server will authenticate a user using a username and password?

https://docs.nats.io/nats-server/configuration/securing_nats/auth_intro/username_password

Or did I misunderstand?

Thanks

**Comment by sasbury** [comment]
Yes, you can do user/password - here are a couple examples - somehow the doc page is broken so linking these directly. NATS has several different auth models, some other examples are in that repo if you are curious, and the doc seems to work for those, https://docs.nats.io/developing-with-nats/security :-(

https://github.com/nats-io/java-nats-examples/blob/master/src/main/java/io/nats/examples/ConnectUserPassword.java

https://github.com/nats-io/java-nats-examples/blob/master/src/main/java/io/nats/examples/ConnectUserPasswordURL.java

**Comment by sasbury** [comment]
Feel free to reopen or hit our slack channel if you have more questions...

https://slack.nats.io/
