### ISSUE TITLE
Load-balanced message handler consumers co-ordination

### ISSUE THREAD

**Issue by brvith** [nats-io/nats.java#284]
I have a use-case to block/wait for the dependent messages processing between load balance queue group consumers.

I am trying to build correlation messaging system, with complex business logic in correlation key identification, With current implementation same correlated messages, shall land in different load balance consumers and processed concurrently, without understanding their dependencies, In that case I need to process one by one and co-ordinate between consumers.

I am trying to solve the use case similar to distributed locking using NATS itself while processing messages concurrently. 

Do we have an api to get list of consumers for particular subject, then we can communicate to the consumers to create lock/unlock for certain correlated messages.

Right now, I am trying to solve with Atomix, The problem with Atomix is, it requires complex cluster configuration and some cases both share some common functionalities. I feel NATS can handle this well, with simple approach ( lock based on subjects )

https://atomix.io/docs/latest/user-manual/primitives/DistributedLock/

The idea, here is define an API under Message, as below

`            
MessageHandler { message ->

                runBlocking {

                    println("Loadbalance Message Handler: ${message.strData()}")

                    message.lock("correlation-key")

                    process(message ) // Execute sharing and dependent functionality

                    message.unlock("correlation-key")

                }
            }
`

**Comment by kozlovic** [comment]
Let's discuss this issue in https://github.com/nats-io/nats-streaming-server/issues/1015. Closing this for now.
