### ISSUE TITLE
Publishing to encoded connection

### ISSUE THREAD

**Issue by RaddadZ** [nats-io/nats.java#289]
I have two nats clients one is written with Go and the other is written with Java, using both clients from nats-io.
the problem is when i'm using encoded connection in my go client, and to my surprise there is no option to create an encoded connection in java, and normal connection cannot publish or subscribe to topics from encoded connections. Am I doing something wrong here or is it not supported yet in Java? any workarounds?

**Comment by kozlovic** [comment]
Have you look at this?
https://docs.nats.io/developing-with-nats/sending/structure
https://docs.nats.io/developing-with-nats/receiving/structure

**Comment by RaddadZ** [comment]
I did, I tested it by publishing from Java client using the Connection class, and subscribed in Go client using EncodedConn -using the provided struct type "Stock"- and I couldn't receive any messages, yet when I change the Go code to use Conn then it receives the message in nats.Msg type, which translates to: 
`&{updates  [123 34 115 121 109 98 111 108 34 58 34 71 79 79 71 34 44 34 112 114 105 99 101 34 58 49 50 48 48 46 48 125] 0xc0000de180 <nil> <nil>}`  

For now, I'm going to send and receive using Conn and nats.Msg and encode/decode nats.Msg.Data as byte array on both sides.

**Comment by kozlovic** [comment]
OK, but what you could do in your Go receiver, is to set an error handler (add as an option to the Connect() call):
```
opts = append(opts, nats.ErrorHandler(func(_ *nats.Conn, _ *nats.Subscription, err error) {
		log.Printf("Error: %v", err)
}))
nc, err := nats.Connect(url, opts...)
```
and it should report the reason why it can't decode the message. For instance, let's say I have in the Go client this structure:
```
type stock struct {
	Symbol string
	Price  int
}
```
but the Java publisher is incorrectly sending such message:
```
{"symbol":123,"price":1200}
```
Then the Go client would report through the error handler this:
```
Error: nats: Got an error trying to unmarshal: json: cannot unmarshal number into Go struct field stock.Symbol of type string
```
Hope this helps.

**Comment by scottf** [comment]
Please see this example for how to encoded with the java client. https://github.com/nats-io/java-nats-examples/tree/main/encoding
There is nothing built in, but it is trivial.
