### ISSUE TITLE
NatsConnection does not report SSL error

### ISSUE THREAD

**Issue by jimmarino** [nats-io/nats.java#298]
Hi,

NatsConnection throws an IO Exception in a Callable here:

https://github.com/nats-io/nats.java/blob/33dbbf99f453b9c8e985cf6e789826e13a35512a/src/main/java/io/nats/client/impl/NatsConnection.java#L537

However, the exception is never reported here:

https://github.com/nats-io/nats.java/blob/33dbbf99f453b9c8e985cf6e789826e13a35512a/src/main/java/io/nats/client/impl/NatsConnection.java#L435

I'm happy to submit a PR for this but before I do (assuming this is not the intended behavior), I wanted some advice before doing so since I am unfamiliar with the codebase. Should the result be checked for an exception and simply re-thrown so the exception is caught by the catch block on line 503 and cleanup handled properly?

Thanks!

**Comment by scottf** [comment]
There are existing unit tests for this condition, and the IO Exception is thrown

Here is the test, slightly re-written from the version you referenced:
https://github.com/nats-io/nats.java/blob/main/src/test/java/io/nats/client/impl/TLSConnectTests.java#L254

Here is the code in the version you referenced:
https://github.com/nats-io/nats.java/blob/33dbbf99f453b9c8e985cf6e789826e13a35512a/src/test/java/io/nats/client/impl/TLSConnectTests.java#L266
