### ISSUE TITLE
Add compatibility for Java 7 (and Android platform)

### ISSUE THREAD

**Issue by malloth** [nats-io/nats.java#303]
Currently the only thing that prevents this API to be available for older Java based platforms (like Android) is the usage of Duration class in the public API. If this was removed and instead simple Long was used (for milliseconds) then this API could be used also on Android platform. Please consider the removal of this class usage in the public API and lower your Java requirement to 7 or provide a separate artifact which would give Java 7 users the availability of using your library without the need of forking it.

**Comment by kkocel** [comment]
Actually not only `Duration` - lot's of other stuff as well eg. `CompletableFuture` etc.

**Comment by kkocel** [comment]
I see two options here 1. port existing library to support Android specifically, 2. do not use nats directly from Android ( might not be an option )

**Comment by sasbury** [comment]
We thought a lot about this for the 2.x refactor and decided not to support Java 7 and instead to move to Java 8. There is a back port at https://nats.io/download/kedzie/nats-android/ that you can use.
