### ISSUE TITLE
Publish operation fails with a bogus message if the calling thread had been interrupted

### ISSUE THREAD

**Issue by ivanr** [nats-io/nats.java#305]
In 2.6.7, if a publish operation is attempted from a thread that had been interrupted, it fails immediately. If the queue is empty (as it was in my case), the message reads "Output queue is full 0". This is because at some point the library attempts to acquire a lock and that fails if the interrupted flag is set.

Before 2.6.7, the situation is much worse because messages are silently not sent. This can lead to a very confusing situation where one message is sent, the next isn't and so on. In my case I was at 2.5.x and it took me a while to start figuring out what was happening.

But, even in 2.6.7 the message is very confusing and for a while I was convinced I had come across a serious bug in the library. It was only after stepping through the code in the debugger that I figured out the actual problem.

I think it would be useful to add a check for this situation and throw an exception with a different message. The "right" thing to do may be to throw InterruptedException, but any exception with a meaningful message would be a great improvement.

**Comment by scottf** [comment]
@ivanr Can you give me a little information. How did you accomplish the initial interrupted thread. I am adding this to my task list to follow up.

**Comment by scottf** [comment]
@ivanr I commented in #316

**Comment by ivanr** [comment]
@scottf I have an email from you with a question, but I am not seeing it here any more. In any case, my situation was a bug in my code. I have a RPC framework built on top of NATS, with threads and interruption used for task cancellation. The bug was that my code didn't check for thread interruption before calling NATS.

**Comment by scottf** [comment]
@ivanr Great, thanks for getting back to me. I'm closing this issue.
