### ISSUE TITLE
nats.java and testcontainers

### ISSUE THREAD

**Issue by kkocel** [nats-io/nats.java#307]
I've tried to use `nats` as a test container ( https://www.testcontainers.org/ ) 

My test with `nats` container looks like this:

```kotlin
@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
    classes = [
    // ...
    ]
)
@Testcontainers
abstract class IntegrationTest {

    companion object {
        internal lateinit var natsUrl: String

        class KGenericContainer(imageName: String) : GenericContainer<KGenericContainer>(imageName)

        @Container
        private val nats = KGenericContainer("nats:latest")
            .withExposedPorts(4222, 8222)
            .waitingFor(LogMessageWaitStrategy().withRegEx(".*Server is ready.*"))

        @DynamicPropertySource
        @JvmStatic
        fun setupProperties(registry: DynamicPropertyRegistry) {
            natsUrl = "nats://${nats.containerIpAddress}:${nats.getMappedPort(4222)}"
        }

    }

        @Test
        fun `my test`(){
            val natsConnection = Nats.connect(natsUrl)
            // ...
        }

```

When I run this test as the only one - everything is fine. 
But when I run a batch of similar tests I get:

```
java.io.IOException: Unable to connect to NATS servers: nats://localhost:33633.
	at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:236)
	at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29)
	at io.nats.client.Nats.createConnection(Nats.java:249)
	at io.nats.client.Nats.connect(Nats.java:131)
```

**Comment by sasbury** [comment]
I have no testcontainer experience, but i am confused that the URL has "containerIPAddress" but the error has "localhost", i wonder if something is blocking the KGenericContainer after a certain count?

**Comment by kkocel** [comment]
@sasbury `containerIpAddress` points to docker container - usually, it's localhost. 

I tried to debug and it seems that there is no exception on `nats` client-side, but it's not connected - maybe it's related with concurrency?

**Comment by sasbury** [comment]
i wonder if it is related to spinning up nats-server for every test somehow.

**Comment by kkocel** [comment]
@sasbury if you want I can share sample project with you that has this exact issue. Since cause might be in:
 1) nats container itself 
 2) testcontainers library 
 3) test structure
 4) nats.java

**Comment by scottf** [comment]
@kkocel Is this still an issue? Why is your code trying to connect to nats://localhost:33633, is this the way TestContainer works?

Are you trying to run a nats server in a unit test? If so you have 2 other options. 
1. you can look at the unit tests for our client. https://github.com/nats-io/nats.java/blob/master/src/test/java/io/nats/client/NatsTestServer.java
2. Check out this project: https://github.com/YunaBraska/nats-streaming-server-embedded

**Comment by kkocel** [comment]
@scottf test containers setup docker image and assign random mapped ports to the image (it's how Docker works I assume).
However, I submitted PR to testcontainers that adds NATS support: https://github.com/testcontainers/testcontainers-java/pull/3888

**Comment by scottf** [comment]
Solution provided, no response, closing.
