### ISSUE TITLE
Benchmark Reporting is inaccurate

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.java#315]
This was shared by a user:

```bash
$ java -cp dependency/*:nats-benchmarks-0.0.1-SNAPSHOT.jar  io.nats.examples.benchmark.NatsBench -s nats://<redacted>:4223 -np 1 -ns 0 -ms 1024 -n 1 showcase.benchmark.simple

Starting benchmark(s) [msgs=1, msgsize=1024, pubs=1, subs=0]
Current memory usage is 339.78 mb / 358.50 mb / 5.19 gb free/total/max
INFO  - Use ctrl-C to cancel.
INFO  - Current date time: Thu May 21 15:59:41 CDT 2020
 
Discovered NATS Servers: nats://<redacted>:4222
Discovered NATS Servers:<redacted>:4223
Connected NATS Server: nats://<redacted>:4223 - Event :nats: connection opened
Connected NATS Server: nats://<redacted>:4223 - Event :nats: connection opened
Unable to stop reader thread
Connection to NATS servers closed
INFO  - Pub Only stats: 288 msgs/sec ~ 288.75 kb/sec
 
INFO  - Successfully Published messages: 4
INFO  - Successfully Received messages: 0
Final memory usage is 296.56 mb / 358.50 mb / 5.19 gb free/total/max
INFO  - Current date time: Thu May 21 16:01:05
```

**Comment by sasbury** [comment]
Which part is inaccurate, maybe I can't see it well on my phone?On May 26, 2020 3:34 PM, Colin Sullivan <notifications@github.com> wrote:
This was shared by a user:
$ java -cp dependency/*:nats-benchmarks-0.0.1-SNAPSHOT.jar  io.nats.examples.benchmark.NatsBench -s nats://<redacted>:4223 -np 1 -ns 0 -ms 1024 -n 1 showcase.benchmark.simple

Starting benchmark(s) [msgs=1, msgsize=1024, pubs=1, subs=0]
Current memory usage is 339.78 mb / 358.50 mb / 5.19 gb free/total/max
INFO  - Use ctrl-C to cancel.
INFO  - Current date time: Thu May 21 15:59:41 CDT 2020
 
Discovered NATS Servers: nats://<redacted>:4222
Discovered NATS Servers:<redacted>:4223
Connected NATS Server: nats://<redacted>:4223 - Event :nats: connection opened
Connected NATS Server: nats://<redacted>:4223 - Event :nats: connection opened
Unable to stop reader thread
Connection to NATS servers closed
INFO  - Pub Only stats: 288 msgs/sec ~ 288.75 kb/sec
 
INFO  - Successfully Published messages: 4
INFO  - Successfully Received messages: 0
Final memory usage is 296.56 mb / 358.50 mb / 5.19 gb free/total/max
INFO  - Current date time: Thu May 21 16:01:05

**Comment by sasbury** [comment]
I am confused by this unable to stop reader thread, i haven't seen that before. But I am not sure which stats are wrong?

**Comment by scottf** [comment]
closing needed more information
