### ISSUE TITLE
Add a simple way to connect using NATS 2.0 credentials.

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.java#321]
e.g.

`Nats.Connect("localhost", my.creds);`

**Comment by olicuzo** [comment]
Hi, I would like to help on this if possible, I'm getting to know the library and contributing seems to be the best way.

**Comment by matthiashanel** [comment]
@olicuzo Thanks for your contribution. 
@ColinSullivan1 I'll close this due to the merged change
