### ISSUE TITLE
Automatically Upgrade to TLS

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.java#322]
If the server requests a TLS connection, identified via the "tls_required" flag in the server's info struct sent to the client in the connect handshake, the client should attempt to automatically upgrade to TLS if possible.

See https://github.com/nats-io/nats.net/pull/372 or [connect logic in nats.go](https://github.com/nats-io/nats.go/blob/e08031f0cc30b51a7585de68fd6bce075688f3d4/nats.go#L1642) for reference.

**Comment by brimworks** [comment]
@ColinSullivan1 the java client has this logic:

https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/impl/NatsConnection.java#L512

...are you suggesting that if the server returns `tls_required=true` and the client does NOT require TLS we should still connect over TLS? ...and avoid throwing that exception?
