### ISSUE TITLE
NATS client leaves dangling threads after close, if NATS server was down when drain & close were invoked

### ISSUE THREAD

**Issue by adamkotwasinski** [nats-io/nats.java#324]
Hey, first and foremost thanks for creating NATS Java client.

I found that NATS connection leaves dangling non-daemon threads after `.drain` & `.close` methods have been invoked, potentially leaking resources.

Very simple example (run it with NATS server running):
```
    public static void main(final String[] args) throws Exception {

        // We connect without exceptions.
        final Connection connection = Nats.connect();

        // Now kill the server and kick off shutdown.
        System.in.read(new byte[2]);
        LOG.info("shutting down (server is dead now)");
        try {
            final CompletableFuture<Boolean> drainFuture = connection.drain(Duration.ofSeconds(5));
            LOG.info("drain: {}", drainFuture.get()); // Throws, as expected.
        }
        catch (final Exception e) {
            LOG.error("drain", e);
        }
        finally {
            connection.close(); // Returns okay.
        }

        // Main thread finishes.
        LOG.info("finished");
    }
```
what results in main thread finishing, but us having non-daemon `NATS Connection Timer` thread and one of (potentially daemon) worker threads:
<img width="325" alt="Screen Shot 2020-07-22 at 13 50 48" src="https://user-images.githubusercontent.com/17969711/88227538-9ccf3100-cc22-11ea-84c8-2f4cf4ddb42d.png">

After some time, the worker thread finally finishes, but it turns out that Connection Timer was never cleaned up:
<img width="328" alt="Screen Shot 2020-07-22 at 13 50 18" src="https://user-images.githubusercontent.com/17969711/88227628-ba9c9600-cc22-11ea-99b1-7355550c3e40.png">

I think the cause is that it's possible for `close()` to end early in https://github.com/nats-io/nats.java/blob/2.6.8/src/main/java/io/nats/client/impl/NatsConnection.java#L624 (after all, we wanted to drain, but just failed).

Changing worker threads to daemons would not help, as the timer itself is not a daemon (https://github.com/nats-io/nats.java/blob/2.6.8/src/main/java/io/nats/client/impl/NatsConnection.java#L462). And anyways, that would not be viable for users that want to initialize NATS connection multiple times over lifetime of VM (e.g. in application containers).

**Comment by matthiashanel** [comment]
@adamkotwasinski , thanks for submitting this issue. I have verified it and am now weighing my options for a fix.

**Comment by matthiashanel** [comment]
@sasbury @ColinSullivan1 , this leak happens because the fetch inside drain fails (https://github.com/nats-io/nats.java/blob/4dbb1d405780f9326fddbf63858f700dc673fc14/src/main/java/io/nats/client/impl/NatsConnection.java#L1794). When this happens close will never make it past the draining check and thus won't perform the cleanup.

When flush throws an exception, I see two options:

1. Set draining to null again (tracker won't be returned anyway) OR
2. Proceed as if flush had passed (possibly bypassing some of the other code and just calling close(checkDrainStatus = false)

I'm relatively new to java's futures api, do you have a preference? 
(2 is probably the cleanest but most intrusive in terms of behavior change)

**Comment by ColinSullivan1** [comment]
I see the comment that exceptions in flush were intended to be thrown back to the caller...   So I suggest wrapping the flush in a try/catch, then in the catch cleanup up resources (`this.close(false);`) and throwing the original exception back up.

e.g. something like:

```java
try {
    this.flush(timeout); // Flush and wait up to the timeout, if this fails, let the caller know
} catch (Exception e) {
    this.close(false);
    throw e;
}
``` 

There may be more cleanup to do but I think this could resolve the problem and keep the original behavior (and the authors intent).
