### ISSUE TITLE
Add Message Headers

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.java#335]
Add message header support:

- https://github.com/nats-io/nats.go/pull/560
- https://github.com/nats-io/nats.go/pull/582
- https://github.com/nats-io/nats.net/pull/394

**Comment by RichardHightower** [comment]
seems related to this too

https://github.com/nats-io/nats-server/pull/1383

**Comment by RichardHightower** [comment]
spec. https://github.com/nats-io/nats-server/blob/master/doc/adr/0004-nats-headers.md

**Comment by ColinSullivan1** [comment]
Resolved in #362
