### ISSUE TITLE
Why is a char[] more secure then a String for connection auth details?

### ISSUE THREAD

**Issue by chris13524** [nats-io/nats.java#341]
The javadocs just say this is for ["better security"](https://github.com/nats-io/nats.java/blob/master/src/main/java/io/nats/client/Options.java#L1056), but it is unclear why using a char array is better. Particularly when I would just call `toCharArray()` on my strings to workaround this...which this is what [`userInfo(String, String)`](https://github.com/nats-io/nats.java/blob/master/src/main/java/io/nats/client/Options.java#L1059) does already, even though it is deprecated and supposedly less secure.

Is there a more secure way to convert String -> char[]?

Ref: #252, #254

**Comment by scottf** [comment]
@chris13524 @derekcollison @RichardHightower This article explains it well: https://www.tutorialspoint.com/why-char-array-is-more-secure-store-sensitive-data-than-string-in-java
