### ISSUE TITLE
Performance issue when publishing to certain topics

### ISSUE THREAD

**Issue by PlatanoBailando** [nats-io/nats.java#344]
Hi all,

I've discovered a weird quirk with certain subjects and performance.  If a subject matches the regex ".\*sub.\*", then the performance in jnats drops by at least a factor of 10.  I'm not sure why this is.  You can verify this rather easily by taking the autobench code and changing the getSubject() method to return some string matching that regex.

Funny enough, I don't think this occurs with TLS on, but not 100% sure.  I'm also guessing the problem exists in jnats, because the go program nats-bench doesn't seem to have the same issue and the issue occurs for even just publishing messages.

Versions:
jnats 2.6.6
nats-server 2.1.8

Examples:
Normal Benchmarks:

> Task :NatsAutoBench.main()
Connecting to NATS server at nats://localhost:4321
Running warmup
Current memory usage is 226.27 mb / 256.00 mb / 3.97 gb free/total/max
Executing tests .........................
> 
> PubOnly 0                 1,000            389,165 msg/s       0.00 b/s
PubOnly 8                 1,000            330,163 msg/s      2.52 mb/s
PubOnly 32                1,000            126,361 msg/s      3.86 mb/s
PubOnly 256               1,000             20,482 msg/s      5.00 mb/s
PubOnly 512               1,000             10,598 msg/s      5.18 mb/s
> 
> PubSub 0                  1,000            362,673 msg/s       0.00 b/s
PubSub 8                  1,000            310,964 msg/s      2.37 mb/s
PubSub 32                 1,000            104,960 msg/s      3.20 mb/s
PubSub 256                1,000             27,154 msg/s      6.63 mb/s
PubSub 512                1,000             14,420 msg/s      7.04 mb/s
> 
> PubDispatch 0             1,000            263,414 msg/s       0.00 b/s
PubDispatch 8             1,000            394,866 msg/s      3.01 mb/s
PubDispatch 32            1,000            132,041 msg/s      4.03 mb/s
PubDispatch 256           1,000             27,492 msg/s      6.71 mb/s
PubDispatch 512           1,000             15,946 msg/s      7.79 mb/s
> 
> ReqReply 0                    2                655 msg/s       0.00 b/s
ReqReply 8                    2                876 msg/s      6.84 kb/s
ReqReply 32                   1                721 msg/s     22.56 kb/s
ReqReply 256                  1                689 msg/s    172.50 kb/s
ReqReply 512                  1                648 msg/s    324.19 kb/s
> 
> Latency 0         5    374 / 472.00 / 500    +/- 251.22  (microseconds)
Latency 8         5    386 / 429.20 / 484    +/- 239.74  (microseconds)
Latency 32        5    400 / 449.90 / 501    +/- 250.38  (microseconds)
Latency 256       5    453 / 538.40 / 584    +/- 294.85  (microseconds)
Latency 512       5    397 / 428.50 / 609    +/- 276.90  (microseconds)
> 
> Final memory usage is 5.89 mb / 8.00 mb / 3.97 gb free/total/max

Benchmarks with subject "this.is.a.bad.subject.for.some.reason"

> Task :NatsAutoBench.main()
Connecting to NATS server at nats://localhost:4321
Running warmup
Current memory usage is 218.12 mb / 256.00 mb / 3.97 gb free/total/max
Executing tests .........................
> 
> PubOnly 0                 1,000             14,072 msg/s       0.00 b/s
PubOnly 8                 1,000             14,998 msg/s    117.18 kb/s
PubOnly 32                1,000             13,479 msg/s    421.25 kb/s
PubOnly 256               1,000              7,356 msg/s      1.80 mb/s
PubOnly 512               1,000              5,334 msg/s      2.60 mb/s
> 
> PubSub 0                  1,000             15,486 msg/s       0.00 b/s
PubSub 8                  1,000             13,736 msg/s    107.32 kb/s
PubSub 32                 1,000             14,538 msg/s    454.34 kb/s
PubSub 256                1,000             10,440 msg/s      2.55 mb/s
PubSub 512                1,000              7,388 msg/s      3.61 mb/s
> 
> PubDispatch 0             1,000             14,760 msg/s       0.00 b/s
PubDispatch 8             1,000             13,696 msg/s    107.00 kb/s
PubDispatch 32            1,000             14,690 msg/s    459.08 kb/s
PubDispatch 256           1,000             10,734 msg/s      2.62 mb/s
PubDispatch 512           1,000              8,056 msg/s      3.93 mb/s
> 
> ReqReply 0                    2                626 msg/s       0.00 b/s
ReqReply 8                    2                810 msg/s      6.33 kb/s
ReqReply 32                   1                775 msg/s     24.23 kb/s
ReqReply 256                  1                600 msg/s    150.07 kb/s
ReqReply 512                  1                540 msg/s    270.36 kb/s
> 
> Latency 0         5    438 / 548.20 / 745    +/- 314.75  (microseconds)
Latency 8         5    438 / 609.10 / 663    +/- 321.49  (microseconds)
Latency 32        5    495 / 530.40 / 718    +/- 326.90  (microseconds)
Latency 256       5    395 / 602.10 / 799    +/- 349.26  (microseconds)
Latency 512       5    497 / 620.10 / 707    +/- 343.75  (microseconds)
> 
> Final memory usage is 5.89 mb / 8.00 mb / 3.97 gb free/total/max

**Comment by sasbury** [comment]
I am curious if this happens with other clients?

**Comment by PlatanoBailando** [comment]
The only other one I tried was nats-bench, which did not exhibit this problem as near as I could tell.

**Comment by scottf** [comment]
I ran the PubOnly portion of this against the latest server today and also did not see this issue. There have been many changes to that server (mostly for Jetstream) in the last 5 months. There have also been a few changes for performance in the client, specifically some flushing when publishing. I will run a full benchmark tonight, but I'm encouraged that I did not see this.
