### ISSUE TITLE
Jnats should use non-blocking NIO2 Sockets instead of legacy blocking IO.

### ISSUE THREAD

**Issue by jameshilliard** [nats-io/nats.java#347]
Currently it appears Jnats is using legacy blocking socket streams for the `SocketDataPort` implementation, this should probably be migrated to use a non-blocking NIO2 [AsynchronousSocketChannel](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/AsynchronousSocketChannel.html) for improved performance/latency along with thread safety. I'll probably try and do this myself once #346 is merged.

https://github.com/nats-io/nats.java/blob/031b245f2e66b16c9153cafe0c3a42b374040597/src/main/java/io/nats/client/impl/SocketDataPort.java#L37-L41

Is there any reason that Jnats has avoided using NIO2 sockets that I should be aware of? From my initial reading of the code converting to NIO2 sockets should be fairly straight forward as Jnats seems to use the NIO based `ByteBuffer`'s already for messages which is the same buffer format NIO2 based sockets expect for reading/writing.

**Comment by brimworks** [comment]
Track this need here: https://github.com/nats-io/nats.java/issues/317

Basically, we all want an async client, so let's track that need in the above issue.

Thanks!
