### ISSUE TITLE
Automatic module name

### ISSUE THREAD

**Issue by bjorndarri** [nats-io/nats.java#355]
Hi,

Would you consider adding an Automatic-Module-Name clause to the jar manifest?

```groovy
manifest {
     attributes(
        'Automatic-Module-Name': 'io.nats.jnats',
    )
}
```

Thanks.

**Comment by scottf** [comment]
@bjorndarri We are probably going to add this in. Since the client is open source, have you gotten a copy of the source and done this? I'm assuming that you are using modules in your application, can you help us understand what problem this solves?

**Comment by bjorndarri** [comment]
I'm using this library in a fully modular Java application, using Gradle (without the [gradle-modules-plugin](https://github.com/java9-modularity/gradle-modules-plugin)). It's basically just a hazzle using non-modularized libraries in modular applications (build file bloat), so I added this little change and am using my own SNAPSHOT version of nats.io. Without this Java falls back to automatic module naming using the .jar filename, which is, apart from it just being a hazzle, quite fragile.

Adding this manifest directive is the simplest way to allow usage both with Java 8 and modularized Java > 9 applications.

Here's some additional information:
[Automatic-Module-Name: Calling all Java Library Maintainers](http://branchandbound.net/blog/java/2017/12/automatic-module-name/)
and
[Explicitly Naming Automatic Java Modules](https://dzone.com/articles/explicitly-naming-automatic-java-modules)
