### ISSUE TITLE
Validations on expectedLastSeqence, expectedStream and expectedLastMsgId are not working for jetstream producer

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats.java#384]
Validations on expectedLastSeqence, expectedStream and expectedLastMsgId are not working for jetstream producer. It works with any random values. Expected output is with any random sequence, stream and msg id it should validate and throw proper error message to user.

**Comment by ColinSullivan1** [comment]
@gstaware, this will be available in the master branch / nightly docker builds of the NATS server until v 2.2 of the server is released.
