### ISSUE TITLE
Websocket Support - Java

### ISSUE THREAD

**Issue by brimworks** [nats-io/nats.java#399]
I'm working on a project which requires connections to be established over HTTP (potentially over an HTTP proxy). To that end, I was planning to write a `DataPort` implementation which checks if the `serverURI` has a scheme of "ws" (or "wss" if secure is desired) and then performs an HTTP connection (potentially respecting any desire to use a proxy).

Is there any pre-existing code which might already implement this?

If not, is there others which would benefit from this code being contributed back to this project?

Thanks,
-Brian

**Comment by brimworks** [comment]
I've posted a PR to add this support here: https://github.com/nats-io/nats.java/pull/426

**Comment by emmanuelandre** [comment]
Hi, we are interested in this. Will it be merged anytime soon?
