### ISSUE TITLE
createContext() not documented

### ISSUE THREAD

**Issue by oliverhausler** [nats-io/nats.java#423]
In https://github.com/nats-io/nats.java/blob/master/README.md#tls, the "examples.md" link https://github.com/nats-io/nats.java/blob/master/src/examples/java/io/nats/examples/examples.md returns 404.

I remember `createContext()` was documented somewhere, and I remember it because it was the cleanest, most elaborate piece of code for building an SSLContext in Java (which per-se is kind of messy). Now I can't find it.

_I am trying to add a custom cert from a PEM file (which is injected by k8s) but I am not managing to wire this into NATS. I think the `createContext()` piece of code would help._

**Comment by scottf** [comment]
@oliverhausler Here are some places in the code that may help
https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/support/SSLUtils.java
https://github.com/nats-io/nats.java/blob/main/src/test/java/io/nats/client/TestSSLUtils.java
