### ISSUE TITLE
Build is failing to deploy

### ISSUE THREAD

**Issue by scottf** [nats-io/nats.java#444]
Objects signatures are calculated before they are deployed. It appears that the current build is deploying a file that was modified after it's signature was calculated, so the uploaded files does not match the signature.

In order to test fixes I must push code in the master branch and then provide a tag. I would like to be allowed to merge without reviews. To protect the integrity of the branch I am doing the following:

1. copy the current master branch to a new branch https://github.com/nats-io/nats.java/tree/master-backup-issue-444
2. changing the version number to 0.0.210, which I will change back to 2.10.0 once the issue is resolved
3. for testing after merge, I will tag 0.0.210.1, 0.0.210.2 to test builds. I will delete these tags when testing is done.

**Comment by ColinSullivan1** [comment]
Feel free to push travis related changes to master w/o review to expedite this.

**Comment by scottf** [comment]
closing, resolved without needing to merge
