### ISSUE TITLE
examples.md link broken 

### ISSUE THREAD

**Issue by aashikam** [nats-io/nats.java#469]
the link for  examples.md in Basic Usage gives a 404
https://github.com/nats-io/nats.java/blob/main/src/examples/java/io/nats/examples/examples.md

<img width="896" alt="Screenshot 2021-05-17 at 08 09 01" src="https://user-images.githubusercontent.com/39673615/118425653-41a58800-b6e7-11eb-9418-25a78ddadf9b.png">
<img width="943" alt="Screenshot 2021-05-17 at 08 09 24" src="https://user-images.githubusercontent.com/39673615/118425662-44a07880-b6e7-11eb-8629-6b45e3829557.png">

**Comment by scottf** [comment]
Thanks for catching that, fixing https://github.com/nats-io/nats.java/pull/470
