### ISSUE TITLE
JetStream Stream Group leader unable to failover

### ISSUE THREAD

**Issue by SkyStrike** [nats-io/nats.java#486]
Currently I have the following environment
- 3 x JetStream enabled nats server (nats-c01-s01, nats-c01-s02, nats-c01-s03) clustered in docker within a single VM instance. 
- JetStream Stream named 'main'  created. 
- 1 x Subscriber to the cluster (all 3 server IP and ports specified in the client options) subscribing to 'main'
- 1 x Publisher to the cluster (all 3 server IP and ports specified in the client options) subscribing to 'main'

When all the servers are up, the subscriber can connect and receive messages without issues. But when the "Stream Group leader" of 'main' goes offline, the publisher will fail to publish any messages. There is no failover to re-elect the "Stream Group leader" Is this the expected behavior of the cluster? or am I missing some configurations?

Attempts to publish to 'main' will result in 
```
java.io.IOException: Error Publishing: No stream available.
```

The following are the main codes I've used for connection to the cluster, creating the stream, getting JetStream instance.

Server Connection
```
String[] allServers = {"nats://192.168.42.100:4001", "nats://192.168.42.100:4002", "nats://192.168.42.100:4003"};
Options o = new Options.Builder()
    .servers(allServers)
    .build();
Connection nc = Nats.connect(o);
```
Stream Creation
```
//stream creation
JetStreamManagement jsm = nc.jetStreamManagement();
StreamConfiguration streamConfig = StreamConfiguration.builder()
   .name(streamName)
   .storageType(StorageType.File)
   .replicas(1)
   .subjects("main")
   .build();
jsm.addStream(streamConfig);
```

JetStream instance
```
JetStream js = nc.jetStream();
```

Publishing code.
```
Message msg = NatsMessage.builder()
   .subject("main")
   .data("test message", StandardCharsets.UTF_8)
   .build();
PublishAck pa = js.publish(msg);
```

Cluster Config
```
# the config is the same for all 3 servers except the server name. nats-c01-s01, nats-c01-s02, nats-c01-s03
server_name=nats-c01-s01 

listen=4222
http_port: 8222

jetstream {
   store_dir=/nats/storage
}

cluster {
  name: c01
  listen: 0.0.0.0:6222
  routes: [
    nats-route://nats-c01-s01:6222
    nats-route://nats-c01-s02:6222
    nats-route://nats-c01-s03:6222
  ]
}
```

**Comment by scottf** [comment]
@SkyStrike can you try setting your stream replication factor to 3 and see what happens? Our initial guess is that since you don't replicate, there is no data except in the server you initially connect to. Also, if you have more questions, can you follow up with me directly, you can find me on the natsio.slack.com

**Comment by SkyStrike** [comment]
@scottf Thank You! It is due to the replication factor. Once I've set it to 3, the leader election takes place after a certain time.
