### ISSUE TITLE
Behavior of JetStream Replicas, Cross Datacenter Supercluster, High Availability

### ISSUE THREAD

**Issue by SkyStrike** [nats-io/nats.java#488]
Currently I'm simulating a cross Datacenter Supercluster as such

## Cluster Environment
- nats-c01 (simulating DC 1)
    - nats-c01-s01
    - nats-c01-s02
    - nats-c01-s03
- nats-c02 (simulating DC 2)
    - nats-c02-s01
    - nats-c02-s02
    - nats-c02-s03
- nats-c03 (simulating DC 3)
    - nats-c03-s01
    - nats-c03-s02
    - nats-c03-s03

## Cluster Config
All Nodes are setup as gateway similar to the following configuration
```
server_name=nats-c01-s01
listen=4222
http_port: 8222

jetstream {
   store_dir=/nats/storage
}

cluster {
  name: c01
  listen: 0.0.0.0:6222
  routes: [
    nats-route://nats-c01-s01:6222
    nats-route://nats-c01-s02:6222
    nats-route://nats-c01-s03:6222
  ]
}


gateway {
  name: c01
  listen: 0.0.0.0:7222

  authorization {
      user: gwu
      password: gwp
  }

  gateways: [
      { name: "c01", urls: [
          "nats://gwu:gwp@192.168.41.100:7001",
          "nats://gwu:gwp@192.168.41.100:7002",
          "nats://gwu:gwp@192.168.41.100:7003"
      ]},
      { name: "c02", urls: [
          "nats://gwu:gwp@192.168.41.101:7001",
          "nats://gwu:gwp@192.168.41.101:7002",
          "nats://gwu:gwp@192.168.41.101:7003"
      ]},
      { name: "c03", urls: [
          "nats://gwu:gwp@192.168.41.102:7001",
          "nats://gwu:gwp@192.168.41.102:7002",
          "nats://gwu:gwp@192.168.41.102:7003"
      ]}
  ]
}
```

## Client Publisher
A Java publisher is started with all 9 Nodes specified in the connection
```
String[] allServers = { all node ip and ports };
Options o = new Options.Builder()
    .servers(allServers)
    .build();
Connection nc = Nats.connect(o);
JetStream js = nc.jetStream();

//publish a message
Message msg = NatsMessage.builder()
   .subject("main")
   .data("test message", StandardCharsets.UTF_8)
   .build();
PublishAck pa = js.publish(msg);
```

## Observations
I have noticed the following
1) The max replica I can set in the above environment is 3. Any more than 3 will result in `insufficient resources (503)` and any more than 5 will result in `Replicas must be from 1 to 5 inclusive.`
2) Assuming the publsher is connected to "nats-c01-s01", when a stream is created (subject=`main`, replica=`3`), 1 of the 3 in the same cluster will become the subject leader, while the other 2 will become backup/secondary.

## Question
In the event of a Datacenter blackout (e.g. loss connectivity to cluster `nats-c01`), publishing to subject `main` will fail. 
1) Is there any way to configure such that nodes residing in `nats-c02` and `nats-c03` can become the leader of subject `main`? 
2) If the publisher hosted needs to be resilient to such DC connectivity loss, is it more recommended to use a single large cluster that stretch across Datacenter? But by doing so, it will still be subjected to the max replicas of 5, will be possible to have a replica larger than 5?

**Comment by scottf** [comment]
@SkyStrike this is a server question, not a java client question. Can you please go to our slack and ask your question?

**Comment by SkyStrike** [comment]
My apologies. will scan thru the Nats server opened list before reposting. 

Thanks.

**Comment by gabel** [comment]
> My apologies. will scan thru the Nats server opened list before reposting.
> 
> Thanks.

Any solution on this found?
