### ISSUE TITLE
Expose length of outgoing queue

### ISSUE THREAD

**Issue by wjbakker** [nats-io/nats.java#509]
The NatsConnection has an outgoing message queue. We would like to expose the actual length of the outgoing queue, so it can be used by application monitoring frameworks (like e.g. Micrometer)

### Proposed API change

A new method is added to the `Connection` interface:

```java
public interface Connection {
    /**
     * @return the length of the outgoing queue.
     */
    long getOutgoingQueueLength();
}
```

### See also:
* #306

**Comment by scottf** [comment]
@wjbakker The outgoing queue length is never very many items, but regardless it is a concept that is being considered for change or removal for performance improvements. I think you want to leverage Statistics anyway. Please see the Connection method getStatistics()

**Comment by wjbakker** [comment]
@scottf Thanks for your feedback. I agree the outgoing queue should be small, however we have seen queue buildup that we want to monitor. You mention the concept is being considered for change, are there open issues describing this change that I can subscribe to?

Thanks for directing to the Statistics. Unfortunately, these statistics do not contain a metric for the outgoing queue. Would you be willing to accept a pull request on adding the outgoing queue length to the statistics?

E.g.
```java
public interface Statistics {
    /**
     * @return the number of messages that are pending in the outgoing queue of this connection.
     */
    public long getOutQueueMsgs();
}
```
