### ISSUE TITLE
NatsJetStream is only checking exact matches for filter subject / add check for whether subject is a subset of filter subject

### ISSUE THREAD

**Issue by ao508** [nats-io/nats.java#514]
The comment here indicates that the subject for a given subscriber can be a subset of the existing filter subject but the only check happening [here](https://github.com/nats-io/nats.java/blob/2.10.0/src/main/java/io/nats/client/impl/NatsJetStream.java#L424) is for an exact match to the existing filter subject. 

So setting up a subscriber for topic `STREAM.topic.sub_topic` for a consumer with filter subject `STREAM.topic.>` fails and throws this [IllegalArgumentException](https://github.com/nats-io/nats.java/blob/2.10.0/src/main/java/io/nats/client/impl/NatsJetStream.java#L427)

**Comment by scottf** [comment]
Let's follow the code you are referring too

1. If we've been asked to subscribe as a durable consumer...
2. If the durable consumer already exists...
3. If the durable consumer set a filter subject...

Your subscription request's filter subject must exactly match the existing durable consumer filter subject.

There is a good example here that shows ephemerals filter subscribing to a subject: https://github.com/nats-io/nats.java/blob/main/src/examples/java/io/nats/examples/jetstream/NatsJsPushSubFilterSubject.java
