### ISSUE TITLE
Nats JetStream server configuration

### ISSUE THREAD

**Issue by divyamadala30** [nats-io/nats.java#515]
There are two places where a consumer/user is setup.

1. In the server.conf file, where the username/password and the permissions are set up
2. Using `nats con add STREAM_NAME`, where the consumer is configured to specific jetstream configurations.

**How does NATs recognize the two users to be the same?**

Examples on how we configured the user and consumer:

- server.conf:
    ` {user: username, password: "password", permissions: $PERMISSIONS}`

- consumer statement:
    `nats con add METADB ${consumer_client_name} 
        --target=${consumer_client_name}.METADB 
        --filter=${FILTER_SUB} 
        --ack=${DEF_ACK} 
        --deliver=${DEF_DELIVER} 
        --max-deliver=${DEF_MAX_DELIVER} 
        --sample=${DEF_SAMPLE} 
        --replay=${DEF_REPLAY} 
        --wait=${DEF_WAIT}  
        --user=${NATS_ADMIN_USERNAME} 
        --password="${NATS_ADMIN_PASSWORD}"  
        --server=${NATS_URL} 
        --tlskey=${NATS_TLSKEY} 
        --tlscert=${NATS_TLSCERT} `

All the consumers and users are setup in the same way.  **How would we connect the nats user and jetstream consumer?**

**Comment by scottf** [comment]
@divyamadala30 Are you asking how to connect to a server with a username/password using the Java client?

**Comment by divyamadala30** [comment]
So I setup username/password for each user in the server.conf file. Our services use this for authorization. The usernames and the consumer client names are matched. However, when I run `nats con ls`, I see new consumers being created but expected to see a list of consumer names that i have added using the cli statement above. So how do i tell nats that the username with set permissions is the same consumer with matching consumer-client-name?

**Comment by scottf** [comment]
@divyamadala30 So you are asking about the nats cli, which is not the java client.  You might be better served by posting to our slack channels at natsio.slack.com Also, the cli that you are using is in this repo, https://github.com/nats-io/natscli, but Github issues should be used for bug reporting and feature requests, not technical support.
