### ISSUE TITLE
Can't use Nats.java lib for android < android O

### ISSUE THREAD

**Issue by ngoluuduythai** [nats-io/nats.java#517]
Can't use Nats.java lib for android < Android O.
Because the lib using java.time.Duration only support android > Android O

**Comment by scottf** [comment]
Duration is available in Java 8. What is meant by Android O? maybe you can use the version names identified here: https://en.wikipedia.org/wiki/Android_version_history

**Comment by scottf** [comment]
@ngoluuduythai Duration is available in Java 8. What is meant by Android O? maybe you can use the version names identified here: https://en.wikipedia.org/wiki/Android_version_history. If you have to have that version, you may have to fork the client and remove the uses of duration.

**Comment by ngoluuduythai** [comment]
Thanks for your answer, I just ask does lib support for Android old version lower android O. I will try with the fork solution.
