### ISSUE TITLE
AckWait doesn't seem to be working

### ISSUE THREAD

**Issue by woli** [nats-io/nats.java#545]
I'm using the java client and building the stream consumer like this:

```
var consumerConfig = ConsumerConfiguration.builder()
  .ackPolicy(AckPolicy.Explicit)
  .ackWait(Duration.ofSeconds(60))
  .deliverPolicy(DeliverPolicy.All)
  .durable(durable)
  .build();

var pullOptions = PullSubscribeOptions.builder()
  .configuration(consumerConfig)
  .build();

var sub = stream.subscribe(subject, pullOptions);
```

I pull the messages using the fech api: sub.fetch(10, Duration.ofSeconds(1)).

I'm testing for a scenario where the message handler on the client is very slow and doesn't ack in time. I'd expect to get the message sent again after 60s but no matter the configured value for the AckWait, the message is always sent again after the default 30s.

**Comment by woli** [comment]
Workarround: delete the consumer using natscli

**Comment by scottf** [comment]
I think this is a user error of consumer creation. See the java code I built (545-java.txt) and then the nats cli output after the run (545-cli-out.txt)
[545-cli-out.txt](https://github.com/nats-io/nats.java/files/7180071/545-cli-out.txt)
[545-java.txt](https://github.com/nats-io/nats.java/files/7180072/545-java.txt)

**Comment by scottf** [comment]
Closing this. The ackWait cannot be changed once a consumer is created. This needs to be better documented https://github.com/nats-io/nats.java/blob/main/src/test/java/io/nats/client/impl/JetStreamManagementTests.java#L393

**Comment by scottf** [comment]
I made this issue for our team to discuss. https://github.com/nats-io/nats-architecture-and-design/issues/53
