### ISSUE TITLE
feature: `JetStreamSubscription.fetch` should ignore Exceeded MaxAckPending status message

### ISSUE THREAD

**Issue by vlushn** [nats-io/nats.java#586]
## Feature Request

This is a feature request as a follow-up to #548 . Currently, the `.fetch()` method ignores 404 and 408 status codes (in `PullAutoStatusManager`) but it should (AFAIS) also ignore 409 which is the max ack pending.

#### Use Case:

I am using NATS with a Kotlin application and want to put the received messages into an internal queue (in order to work nicely with `Flow` for example). As such, the promise of the `.fetch()` method is it handles routine status messages for you. If the poll is running within a loop, the application may not have finished acking all the in-flight messages yet.

#### Proposed Change:

The `PullAutoStatusManager` adds `409` status to ignored status list.

#### Who Benefits From The Change(s)?

Anybody who uses the `.fetch()` method

#### Alternative Approaches

Leave as-is, catch the `JetStreamStatusException` and check for `409` and continue.

Of course, I may have misinterpreted how to handle to 409 message.

**Comment by scottf** [comment]
@vlushn I'm asking around on how the other clients handle this. Do you have any code to help me reproduce this?

**Comment by scottf** [comment]
@vlushn I have fixed this in PR  #643 which is waiting to be reviewed and merged.
