### ISSUE TITLE
Fetch is not working correctly

### ISSUE THREAD

**Issue by henrify** [nats-io/nats.java#594]
Based on the docs, I assumed/interpreted that fetch() would block until 'batchSize' messages are availble or until 'maxWait' has elapsed, whichever occurs first. But that doesn't work if at the time of calling fetch() the server doesn't have any messages - instead in that case the fetch() call blocks until 'maxWait', even if new messages are published to the server.

I don't know the codebase at all, but on superficial look the fetch implementation seems obviously broken: it first calls 'pullNoWait' which in the problem case returns nothing, then it calls read() which couple of call levels deeper blocks until the 'maxWait'.

Or have I misunderstood the docs or the fetch() usage?

**Comment by scottf** [comment]
The fetch uses a pattern that has now been built into the server, that of nowait + expire. The idea was to fetch nowait and if there were no messages to try again with an expire to use all the time the user gave. Looking at the implementation, it looks like it almost does that but actually waits double when there are initially no message so I'll check into that.

Based on what's in the Java client API doc, I say your assumption is wrong.
```
Fetch a list of messages up to the batch size, waiting no longer than maxWait.
```
UP TO the batch size, so that means however many messages can be fetched in the time is what you get. If messages are not available right away but come across within the timeout, you should get them.

**Comment by scottf** [comment]
I'll keep this code up to date https://gist.github.com/scottf/80a9647cf7f60d69dd2d56d030ea1015

**Comment by henrify** [comment]
Thanks for your fast reply @scottf 

I tried the Gist and it reproes 100% the behavior I saw: consumer thread blocks for the full 30 seconds, even though publisher publishes at 10 seconds. 

> The fetch uses a pattern that has now been built into the server, that of nowait + expire.

How/why is that pattern better than doing just single 'pullExpiresIn' with same args as given to 'fetch'? (genuine question and not implaying it wouldn't be better -- I'm completely new to NATS and just don't understand the benefit).

I think I'm going to use the library via low level API. Is there a method to get number of messages that have been pulled from the server and are available for nextMessage() call?

**Comment by scottf** [comment]
for messages that are available, look at pending in the message meta data

**Comment by henrify** [comment]
Thanks, so Subscription.getPendingMessageCount(), right?

Regarding the pullNoWait+pullExpiresIn pattern, I do understand the component pieces, but logically I fail to see any benefit from it:

- If I request fetch(200,1000) and the server already has over 200 messages, then the pullExpiresIn would also be satisfied immediately and close, just like pullNoWait does - so in this case there is no benefit from pullNowait?

- If I request fetch(200,1000) and the server initially has less than 200 messages, then if we first do pullNoWait, we need to follow up with a pullExpiresIn anyway - so in this case the end result is exactly the same eiter way, but by using the pattern there is two pulls instead of one. But more importantly, implementing the logic for the pattern is fragile -- as evidenced by this issue.

**Comment by henrify** [comment]
Ah, makes sense, indeed I missed that the reason might be on the server side of the story. Thanks for your comments and explanations.

**Comment by scottf** [comment]
I ended up just using pullExpire. The unit tests needed a tweak in one place to make sure I let the pull expire when I was testing redlivery, but other than that the test are the same.

**Comment by scottf** [comment]
@henrify jnats 2.13.4-SNAPSHOT is available with this fix if you want to test it out. You can look at the PR #596 if you want to see the changes.
