### ISSUE TITLE
KVStore: Dot in key didn't work when request a list of keys in a bucket 

### ISSUE THREAD

**Issue by philmu** [nats-io/nats.java#621]
OS: Linux
Nats-Server: 2.6.6
jnats: 2.14.0

```
// io.nats.client.Connection connection = ...;

final KeyValue bucket = connection.keyValue("bucketname");
bucket.put("Part1.Part2", "value".getBytes());
bucket.get("Part1.Part2").getValue(); // Works. Returns byte[] with 'value' as expected
for (String key : bucket.keys())
{
     System.out.println(key); // Returns 'Part1', Expected 'Part1.Part2'
}

```

I think here is a problem: https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/support/NatsKeyValueUtil.java#L80

Possible solutions:
- Disallow dots in keys
- expand key with additional elements from split[] (NatsKeyValueUtil.java#L80)

**Comment by scottf** [comment]
Good catch. dots are valid so fixed parsing. https://github.com/nats-io/nats.java/pull/622

**Comment by scottf** [comment]
yeah, get key just wraps the `.key` 
```
public String getKey() { return bucketAndKey.key; }
```
