### ISSUE TITLE
Update bucket settings

### ISSUE THREAD

**Issue by philmu** [nats-io/nats.java#623]
## Feature Request
I want to update bucket settings like stream setting (JetStreamManagement::updateStream)
#### Use Case:
In the moment i have to call KeyValueManagement::delete and KeyValueManagement::create, if i want to 'change' the setting (e.g. ttl).
But: All data is lost
A new Method (e.g. KeyValueManagement::updateBucket) would help to keep data.

**Comment by scottf** [comment]
This enhancement has been added and waiting for review: https://github.com/nats-io/nats.java/pull/662

**Comment by scottf** [comment]
Issue has been fixed, will be available in next release.
