### ISSUE TITLE
Retrieve message via timestamp

### ISSUE THREAD

**Issue by Evynglais** [nats-io/nats.java#647]
## Feature Request

Request message via timestamp in JetStreamManagement.

#### Use Case:

Similar to jetStreamManagement.getMessage(String subject, long sequence), but automatically determine the message based on timestamp (OffsetDateTime?).

Also would be nice to be able to purge from a given timestamp as well.

#### Proposed Change:

Add a method to allow retrieving a single message via JetStreamManagement based on message timestamp (or range of timestamps).

**Comment by scottf** [comment]
@Evynglais This would have to be implemented in the server first. You might want to post an issue there.

**Comment by Evynglais** [comment]
Managed to find a workaround for now - consume the message with consumerConfig set to:

```
.deliverPolicy(DeliverPolicy.ByStartTime)
.startTime([timestamp])
```

and then grab the sequence from the first message.

**Comment by scottf** [comment]
Yes, that's a good workaround. If you make a pull subscriber, you can set the batch size to 1 on the pull. Still seems like a reasonable request for the server though.
