### ISSUE TITLE
Field responsesRespondedTo in NatsConnection produces OOM

### ISSUE THREAD

**Issue by vitalii-honchar** [nats-io/nats.java#658]
## Defect
Field `Map<String, NatsRequestCompletableFuture> responsesRespondedTo` in `NatsConnection` always grows during application runtime and never clean up which leads to out of memory error. Especially that field will be empty after try reconnect to NATS broker, but if there is no tries, so OOM will be produced.

#### Versions of `io.nats:jnats` and `nats-server`:
2.11.2

#### OS/Container environment:
OS: Linux
Docker Image: nats:2.1.7

#### Steps or code to reproduce the issue:
1. Create new connection
2. Send request to connection with method `request`
3. Receive a response to your request
4. Size of `NatsConnection.responsesRespondedTo` was increased, but it never clean up. This leads to OOM.

#### Expected result:
No OOM.

#### Actual result:
OOM.

**Comment by vitalii-honchar** [comment]
Amount of entries in the map under load:
![nats_connection_under_load](https://user-images.githubusercontent.com/20383875/172363634-57bd2114-200f-44af-90b6-a5448cbc9c6a.png)

Amount of entries in the map after load (8 minutes after last load):
![nats_connection_without_load_after_8_minutes png](https://user-images.githubusercontent.com/20383875/172363767-1fb4277f-72ec-4055-91eb-5152ec71178a.png)

I saw that map was cleaned up after load on application was over, I think that was some reconnects to broker.

But when application is under the load heap continuous grows, and during my heap dump analysis continues grows especially `responsesRespondedTo`

**Comment by vitalii-honchar** [comment]
@scottf as I understand it works a little bit different. Let's look on usage of `responsesRespondedTo`.

Method where new items are added in`responsesRespondedTo`:
```Java
void deliverReply(Message msg) {
        boolean oldStyle = options.isOldRequestStyle();
        String subject = msg.getSubject();
        String token = getResponseToken(subject);
        String key = oldStyle ? msg.getSID() : token;
        NatsRequestCompletableFuture f = responsesAwaiting.remove(key);
        if (f != null) {
            responsesRespondedTo.put(key, f);
            statistics.decrementOutstandingRequests();
            if (msg.isStatusMessage() && msg.getStatus().getCode() == 503 && f.isCancelOn503()) {
                f.cancel(true);
            }
            else {
                f.complete(msg);
            }
            statistics.incrementRepliesReceived();
        }
        else if (responsesRespondedTo.get(key) != null) {
            statistics.incrementDuplicateRepliesReceived();
        }
        else {
            statistics.incrementOrphanRepliesReceived();
        }
    }
```
1. When we sent some request to NATS broker we saved that request in our map `responsesAwaiting`
2. When we received some response from NATS broker we are trying to process that response: first try to get something from `responsesAwaiting` for check if we need await for some responses. If there is present some future, we just removes that future from `responsesAwaiting`, passes value to that future and **save link to that future in `responsesRespondedTo`**
3. Problem is in point 2. We save future for track if we will receive two responses for one request in future and we will not this behavior in code
```Java
if (responsesRespondedTo.get(key) != null) {
    statistics.incrementDuplicateRepliesReceived();
}
```
but we never clean up `responsesRespondedTo`.

Cache `responsesRespondedTo` used just for track if we receive two or more responses for one request. But that cache stores data always and never clean up it. So we always need keep a cache filled and never clean up it. This leads to out of memory error.

I see two solutions for this behavior:
1. Completely remove cache `responsesRespondedTo`
2. Expire entries in `responsesRespondedTo` after some timeout, for example if items was in cache during last 5 minutes, remove them.

I tested solution 1 "Completely remove cache `responsesRespondedTo`" and it works fine. System under load has stable heap:
![mobilegw_nats_with_fix_oom](https://user-images.githubusercontent.com/20383875/172414754-2e2402ff-4b8c-4b7e-b16a-6af28a58910c.png)

Heap of system under load with `responsesRespondedTo`:

![mobilegw_nats_without_fix_oom](https://user-images.githubusercontent.com/20383875/172415098-6fd7cb26-07b5-4481-b487-6bc41f27848f.png)

**Comment by scottf** [comment]
`responsesRespondedTo` does clean up after a period of time, there is already an expiration. Please see this code:
https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/support/NatsRequestCompletableFuture.java
and this code:
https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/impl/NatsConnection.java#L978

I suspect the problem is, that under load and many messages, tracking at all could grow this map very large.

So my proposal is to provide options to turn this tracking off. Duplicate messages will be ignored and not counted. There will be an Options option to turn this behavior off and also to set the cleanup timeout padding for when you keep it on. If you need to count them, then the best solution is to reduce the padding timeout.

**Comment by vitalii-honchar** [comment]
Sure I saw that https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/impl/NatsConnection.java#L978 will clean up the map, but as I understand it will be clean up when connection will reconnect to NATS broker.

Option for disable tracking statistics sounds good for me.

**Comment by vitalii-honchar** [comment]
Thank you for #659
