### ISSUE TITLE
Duplicate window in StreamConfiguration is set to 2 min instead of ZERO

### ISSUE THREAD

**Issue by matejbizjak** [nats-io/nats.java#682]
## Defect

When I try to create a stream programmatically using `jetStreamManagement.addStream()` with an unset duplicateWindow in StreamConfiguration a stream should be created with a duplicateWindow set to Duration.ZERO (default value in the StreamConfiguration.Builder). Instead is then overwritten to 2 minutes at the server. Is this the correct behaviour?

StreamConfiguration.Builder().duplicateWindow():
```
/**
 * Sets the duplicate checking window in the the StreamConfiguration.  A Duration.Zero
 * disables duplicate checking.  Duplicate checking is disabled by default.
 * @param window duration to hold message ids for duplicate checking.
 * @return Builder
 */
public Builder duplicateWindow(Duration window) {
    this.duplicateWindow = validateDurationNotRequiredGtOrEqZero(window, Duration.ZERO);
    return this;
}
```

#### `io.nats:jnats` and `nats-server` version:
2.15.3 and 2.8.4
#### OS/Container environment:
Windows and Docker

#### Steps or code to reproduce the issue:
```
StreamConfiguration config = StreamConfiguration.builder()
    .name("stream1")
// ... I also set the subjects and maxMsgs (I didn't set the duplicateWindow)
    .build();
jetStreamManagement.addStream(config);
StreamInfo steamInfo = jetStreamManagement.getStreamInfo("stream1");
```

Value of `steamInfo`:

```
StreamInfo{created=2022-07-01T17:55:48.707221211Z[GMT], StreamConfiguration{name='stream1', description='null', subjects=[subject1, subject2], retentionPolicy=limits, maxConsumers=-1, maxMsgs=100, maxMsgsPerSubject=-1, maxBytes=-1, maxAge=PT0S, maxMsgSize=-1, storageType=memory, replicas=1, noAck=false, template='null', discardPolicy=old, duplicateWindow=PT2M, mirror=null, placement=null, sources=[]}, StreamState{msgs=0, bytes=0, firstSeq=0, lastSeq=0, consumerCount=1, firstTime=0001-01-01T00:00Z[GMT], lastTime=0001-01-01T00:00Z[GMT], subjectCount=0, subjects=null, deletedCount=0, deleteds=[]}, cluster=null, mirror=null, sources=null}
```

#### Expected result:

duplicateWindow=PT0S

#### Actual result:

duplicateWindow=PT2M

**Comment by scottf** [comment]
@matejbizjak If zero is supplied or a value is not supplied, 2 minutes is the default. This has been since at least server version 2.5.0 which is the oldest I have on my machine.
