### ISSUE TITLE
Readme version out of sync with released version.

### ISSUE THREAD

**Issue by yesennes** [nats-io/nats.java#712]
Tiny issue, but still figured you'd want to know, your link to downloading the jar, https://search.maven.org/remotecontent?filepath=io/nats/jnats/2.15.7/jnats-2.15.7.jar is broken.

**Comment by scottf** [comment]
It's fine, it's just because I updated the version at the beginning of the cycle so snapshots would get release properly. I'll think about how to address this, probably have to make the change in 2 passes, once at the beginning of the cycle and once at the end.
