### ISSUE TITLE
Regression since nats clients version 2.16.1 - app hangs on call getStreamInfo()

### ISSUE THREAD

**Issue by stawirej** [nats-io/nats.java#781]
Could you please check regression present in nats clients versions 2.16.1 and 2.16.2?

Execution of  “connection.jetStreamManagement().getStreamInfo(“STREAM_NAME”);” hangs and call doesn’t timeout, throw exception or return value. It just freeze application on this call.
It works on nats client version 2.16.0.

Environment details:

nats:2.8.2-alpine

5.10.0-14-cloud-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7642 48-Core Processor
Stepping:                        0
CPU MHz:                         2299.998
BogoMIPS:                        4599.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0,1

**Comment by scottf** [comment]
Thank you for the report. This has been fixed in this PR https://github.com/nats-io/nats.java/pull/782 and I'm going to do a 2.16.3 release

**Comment by stawirej** [comment]
Thank you @scottf for quick fix. I confirm fix is working.
