### ISSUE TITLE
StreamInfo cached on non existing address

### ISSUE THREAD

**Issue by vasicvuk** [nats-io/nats.java#810]
## Defect

I am using the method  `getStreamInfo` from `JetStreamManagement` to check if the address exists before sending any messages or subscribing to it. It seems that getStreamInfo caches first response and never returns real data even after the address has been created.

Because of this, I need to restart the service in order for it to conclude that there is now a new StreamInfo.

How can we refresh this cache or is there another method we could check if the address is created before asking for StreamInfo?

[Part of code](https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/impl/NatsJetStreamImplBase.java#L120)

Thanks

#### Versions of `io.nats:jnats` and `nats-server`:

2.16.5

#### OS/Container environment:

Alpine 3.16

#### Steps or code to reproduce the issue:

1. Call getStreamInfo
2. Get no information
3. Create a topic
4. Call getStreamInfo within the same process
5. Still no information

#### Expected result:

Expected result is to get the StreamInfo of created address

#### Actual result:

Cached no information

**Comment by scottf** [comment]
I don't think there is bug and I will describe why and will also double check. First, please lets use the word `subject`. Topic is from kafka I suppose I'm just assuming you mean subject.

The implementation of `getStreamInfo(String streamName)` and `getStreamInfo(String streamName, StreamInfoOptions options)` call an internal method
```
StreamInfo _getStreamInfo(String streamName, StreamInfoOptions options) throws IOException, JetStreamApiException {
    String subj = String.format(JSAPI_STREAM_INFO, streamName);
    StreamInfoReader sir = new StreamInfoReader();
    while (sir.hasMore()) {
        Message resp = makeRequestResponseRequired(subj, sir.nextJson(options), jso.getRequestTimeout());
        sir.process(resp);
    }
    return cacheStreamInfo(streamName, sir.getStreamInfo());
}
```
This always goes and makes the request, and then puts the response in the cache.

`StreamInfo.getConfiguration().getSubjects()` will always have the subject as configured in the stream.

`StreamInfo.getState().getSubjects()` will only be populated if you use the second version of `getStreamInfo` that accepts `StreamInfoOptions` and supply `filterSubjects` or `allSubjects`

Please try this.

**Comment by scottf** [comment]
https://github.com/nats-io/nats.java/pull/811/files

**Comment by vasicvuk** [comment]
Hi @scottf,

I am not calling `getSubjects()` at all. I am using code like this:
```
       try {
            JetStreamManagement jsm = connection.jetStreamManagement();
            StreamInfo info = jsm.getStreamInfo(topic);
            return true;
        } catch (Exception ex) {
            return false;
        }
```

and it enters a catch block returning false until I restart the Java service. I check the code quickly and see that there is some sort of cache so I assumed that is the issue. Anyway, I will try to read the exception and open another issue explaining the issue I am having more precisely.

**Comment by scottf** [comment]
Please see the PR with the unit test change. It demonstrates that the `getStreamInfo` call does not call the cache. Also please see the other note that `StreamInfo.getState().getSubjects()` does not get populated unless you use the subject filter.

**Comment by vasicvuk** [comment]
Hi @scottf,

We definitely have some other issue. Thanks for the comments.
