### ISSUE TITLE
Inconsistency between replica setting in [KeyValue|ObjectStore]Configuration and StreamConfiguration

### ISSUE THREAD

**Issue by pskiwi** [nats-io/nats.java#821]
## Defect

`[KeyValue|ObjectStore]Configuration.builder().replicas(0)` and 
`StreamConfiguration.builder().replicas(0)` are handled differently:

 ```java
KeyValueConfiguration kvc = KeyValueConfiguration.builder().name("test").replicas(0).build();
System.out.println(kvc.getReplicas());
StreamConfiguration.builder().name("test").replicas(0).build();      
```
The first  returns 1 and the second throws an exception:
```
1
Exception in thread "main" java.lang.IllegalArgumentException: Replicas must be from 1 to 5 inclusive.
	at io.nats.client.support.Validator.validateNumberOfReplicas(Validator.java:232)
	at io.nats.client.api.StreamConfiguration$Builder.replicas(StreamConfiguration.java:699)
```	
Is this by design?

#### Versions of `io.nats:jnats` and `nats-server`:
2.16.5 / 2.9.10

**Comment by scottf** [comment]
Fixing in https://github.com/nats-io/nats.java/pull/823

**Comment by scottf** [comment]
@pskiwi Fixed and merged to main. Thank you for the bug report.
