### ISSUE TITLE
ServerInfo.getComparableVersion not compatible with NATS Version 2.9.10

### ISSUE THREAD

**Issue by pskiwi** [nats-io/nats.java#822]
## Defect

Checking a NATS 2.9.10 server with `nc.getServerInfo().isOlderThanVersion('2.9.3')` unexpectedly returns `true`.

```java
ServerInfo v2_9_2 = new ServerInfo("{\"version\":\"2.9.2\"}");
ServerInfo v2_9_4 = new ServerInfo("{\"version\":\"2.9.4\"}");
ServerInfo v2_9_10 = new ServerInfo("{\"version\":\"2.9.10\"}");           

System.out.println(v2_9_2.isOlderThanVersion("2.9.3")); // -> true
System.out.println(v2_9_4.isOlderThanVersion("2.9.3")); // -> false
System.out.println(v2_9_10.isOlderThanVersion("2.9.3")); // -> true
```
The root cause seem to be missing braces in `io.nats.client.api.ServerInfo.getComparableVersion(String):` (corrected version)
```java
 return "" + ((Integer.parseInt(v[0]) * 10000) + (Integer.parseInt(v[1]) * 100) + Integer.parseInt(v[2]))
                    + (at == -1 ? "~" : vString.substring(at));
```
without braces:

    2.9.3  -> 200009003~
    2.9.10 -> 2000090010~

with additional braces:

    2.9.3  -> 20903~
    2.9.10 -> 20910~

#### Versions of `io.nats:jnats` and `nats-server`:
2.16.5 / 2.9.10

**Comment by scottf** [comment]
Fixing in https://github.com/nats-io/nats.java/pull/823
