### ISSUE TITLE
NatsObjectStore uses InputStream incorrectly

### ISSUE THREAD

**Issue by ewirch** [nats-io/nats.java#851]
## Defect

`io.nats.client.impl.NatsObjectStore.put(ObjectMeta, InputStream)` reads from `InputStream`. This is the main loop:
```java
            while (red == chunkSize) { // keep reading while last chunk was full size
                red = inputStream.read(buffer);
                if (red > 0) {
                  ...
                }
            }
```

End of the stream is determined by `red != chunkSize`. This violates `InputStream` API contract. From javadoc of `InputStream.read(byte[])`:

> If no byte is available because the stream is at the end of the file, the value -1 is returned; otherwise, at least one byte is read and stored into b.

This leads to a serious problem when using `java.io.SequenceInputStream`:
```java
var buf1 = new byte[10];
var buf2 = new byte[10];
objectStore.put(objectName, new SequenceInputStream(new ByteArrayInputStream(buf1), new ByteArrayInputStream(buf2)));
```
The previous example will read from `buf1`, but ignore the bytes in `buf2`.

 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `io.nats:jnats`: 2.16.8

Side note: This line in the main copy loop:
```java
var payload = red == chunkSize ? buffer : Arrays.copyOfRange(buffer, 0, red);
```
should be 
```java
var payload = red == buffer.length ? buffer : Arrays.copyOfRange(buffer, 0, red);
```
While `chunckSize` and `buffer.length` will always be the same in the current implementation, this is not guaranteed to stay this way in the future. Additionally, `buffer.length` better communicates the intention ("use complete buffer").

**Comment by scottf** [comment]
@ewirch So are you saying that an input stream can return less than the full buffer and also not be done? I didn't think this was the case. So red == -1 is the only condition to stop reading?

**Comment by scottf** [comment]
@ewirch Can you please check out https://github.com/nats-io/nats.java/pull/852

**Comment by ewirch** [comment]
> So are you saying that an input stream can return less than the full buffer and also not be done?

Exactly.

> Can you please check out https://github.com/nats-io/nats.java/pull/852

Looks good.

Out of pure curiosity, why are you caching `buffer.length`?
```java
int bufferLength = buffer.length;
```
Performance? The length of an array is immutable. From the point of view of the JIT compiler (maybe even javac), `bufferLength` is equal to `buffer.length`. But `bufferLength` decreases maintainability. It adds an indirection, increasing the brain parsing overhead for the reading dev, and adds risk of bugs when code is changed.
