### ISSUE TITLE
Allow developer to specify Discovery reply-to for PING requests.

### ISSUE THREAD

**Issue by unixunion** [nats-io/nats.java#856]
At the moment https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/service/Discovery.java#L141 seems to introduce a "-" in the PING reply topic, which cannot be configured via JWT policies. resulting in errors such as:

`Connection: 18, Error: Permissions Violation for Subscription to "fpL1CQIPjr7VRodfcLXN5T-PING"`

I thought "-" was not a valid character for subjects? In either case, allow developers to specify the PING reply to endpoints better. Or switch out the "-" to something within spec.

**Comment by unixunion** [comment]
@scottf , as discussed in Slack.

**Comment by scottf** [comment]
@unixunion please see PR, you are welcome to review/comment.

**Comment by unixunion** [comment]
@scottf tested locally, looks good. Now the PING inbox is working correctly because it can be defined with valid subject.

**Comment by scottf** [comment]
@unixunion Great, thanks for the input and the help, I'll merge.
