### ISSUE TITLE
Option.Builder constructor than can pre-populate from an existing Options object

### ISSUE THREAD

**Issue by davidmcote** [nats-io/nats.java#859]
## Feature Request

Some "*Option.Builders" classes are lacking a constructor that accepts the immutable "*Options" object for pre-populating fields. 

For example, such a constructor can be found in https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/FeatureOptions.java#L52, but no such constructor exists in the main Options.java object used to configure a NATS Connection.

All configuration Builder classes should be copy-constructable from the object they build.

#### Use Case:
1. Constructing Options in multiple stages without passing around a mutable builder.
2. Constructing multiple variations of the same shared constant base Options object.

Eg:
```
public static final Options COMMON_OPTIONS = Options
    .builder()
    ...
    .build();

public Options getApp1Options(String serverUrl) {
    return Options
        .builder(COMMON_OPTIONS)
        .server(serverUrl)
        .build()
}

public Options getApp2Options() {
    return Options
        .builder(COMMON_OPTIONS)
        .connectionListener(aDifferentConnectionListener)
        .build()
}

public Options getApp3Options() {
    return Options
        .builder(COMMON_OPTIONS)
        .alternateValue(123)
        .build()
}

public Options getApp4Options() {
    return Options
        .builder(COMMON_OPTIONS)
        .alternateValue(456)
        .build()
}
```

#### Proposed Change:

In any *Options class missing this pattern, add:
```
class Options {
    public static Options.Builder builder(final Options options) {
        return new Options.Builder(options);
    }

    . . .

    public static class Builder {
        public Builder(final Options options) {
            ... copy from options
        }
    }
}
```

Eg: https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/Options.java and https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/PublishOptions.java

#### Who Benefits From The Change(s)?
Application developers with multiple NATS client components which share only *most* of the information in Options classes.

#### Alternative Approaches
Alternative approaches for application developers who wish to configure Options in separate stages:
1. Wrapper OptionsFactories that return new instances of mutable Builder objects for modification.
2. Or a mirror implementation of Options & Options.Builder classes where staged modification is possible.
3. Implement their own copy-to-Builder utility method and keep it up to date with every field in Options.

Alternative library approaches:
1. Options.Builder(Options.Builder) copy constructor instead of accepting the immutable built class.
2. Options immutable class has a `toBuilder()` instance method that returns a pre-populated Builder rather than the application calling the Builder's constructor or static factory method directly.

**Comment by scottf** [comment]
This seems like a good idea, there are other things that are higher priority for me, but we certainly welcome PRs, please sign all commits.
