### ISSUE TITLE
Add/remove ConnectionListeners after a Connection is constructed.

### ISSUE THREAD

**Issue by davidmcote** [nats-io/nats.java#860]
## Feature Request
I would like to add connection-state listeners to Connections that have already been constructed and are being passed into my business logic from elsewhere in the application.

#### Use Case:
Late and multiple bindings of ConnectionListeners to Connections for business logic to listen for events without needing to construct its own Connection object.

#### Proposed Change:
```
Connection.add/remove(ConnectionListener)
```

#### Who Benefits From The Change(s)?
Applications which separate their NATS Connection factory from their business logic, but whose business logic's resource's lifecycle are coupled to the NATS Connection's.

#### Alternative Approaches
If business logic is interested in tearing down resources when its Connection is closed, it must either:
* Construct the Connection itself with an appropriate ConnectionListener
* Poll the Connection's status
* Accept a custom observable in addition to a Connection that fires when the Connection is closed. (Eg: A ConnectionListener that resolves a CompleteableFuture on CLOSE.)

**Comment by scottf** [comment]
Again good idea here, but low priority, contributions are welcome.

**Comment by davidmcote** [comment]
Thanks Scott!  I've proposed this change in #861

**Comment by scottf** [comment]
Merged, closing
