### ISSUE TITLE
`port out of range:-1` when using `nats` as hostname

### ISSUE THREAD

**Issue by fxnn** [nats-io/nats.java#873]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - 🚫  Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

Providing an analysis here which should easily allow to reproduce the problem in a unit test. If you still need a reproducer, I can try to come up with a proper `docker-compose.yml`, but my main focus is to take relieve any future devs from this pitfall.

#### Steps or code to reproduce the issue:
* run the `nats-server` in a Docker container called `nats`
* configure `jnats` with the URL `nats://nats:4222`

#### Expected result:
connects successfully

#### Actual result:
exception

```
java.io.IOException: java.lang.IllegalArgumentException: port out of range:-1
    at io.nats.client.impl.SocketDataPort.connect(SocketDataPort.java:99)
    at io.nats.client.impl.SocketDataPort.connect(SocketDataPort.java:52)
    at io.nats.client.impl.NatsConnection.tryToConnect(NatsConnection.java:421)
    at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:203)
    at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29)
    at io.nats.client.Nats.createConnection(Nats.java:303)
    at io.nats.client.Nats.connect(Nats.java:210)
```

#### Analysis
1. [`NatsConnection`, line 190](https://github.com/nats-io/nats.java/blob/27d1a7688c5baa823fd09158f307a0e70953db19/src/main/java/io/nats/client/impl/NatsConnection.java#L190) takes the configured URL and resolves the hostname.
2. The URL is updated with the resolved IP address using the `NatsUri::reHost` method [in `NatsConnection`, line 1753](https://github.com/nats-io/nats.java/blob/27d1a7688c5baa823fd09158f307a0e70953db19/src/main/java/io/nats/client/impl/NatsConnection.java#L1753).
3. That method just inserts the hostname with simple string replacement [in `NatsUri`, line 73](https://github.com/nats-io/nats.java/blob/27d1a7688c5baa823fd09158f307a0e70953db19/src/main/java/io/nats/client/support/NatsUri.java#L73). 

As our environment is virtualized, the hostname accidentally equals the protocol name, so the string replacement will change the wrong part of the URL. The error message is not helpful and required a long investigation to find the actual cause.

**Comment by scottf** [comment]
For now you can also workaround with Options.noResolveHostnames

**Comment by scottf** [comment]
@fxnn I fixed this here: https://github.com/nats-io/nats.java/pull/874
