### ISSUE TITLE
WebSocketInputStream incorrectly handles network buffers with multiple WebSocket Frames

### ISSUE THREAD

**Issue by GrafBlutwurst** [nats-io/nats.java#900]
## Defect
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve) (Sadly not applicable since it's non-deterministic, depending on network delivery by server)

The problem is in WebsocketInputStream, in particular here 

```
public int read(byte[] buffer, int offset, int length) throws IOException {
        // Just in case we get headers with empty payloads:
        while (0 == header.getPayloadLength()) {
            if (!readHeader()) {
                return -1;
            }
        }
        if (header.getOpCode() == OpCode.CLOSE) {
            // Ignore the websocket close message body:
            in.skip(header.getPayloadLength());
            return -1;
        }
        length = in.read(buffer, offset, length);
        if (-1 == length) {
            return length;
        }
        return header.filterPayload(buffer, offset, length);
    }
```

This code gets called by NatsConnectionReader with some length `n` and offset 0.

1. we preread the websocket header in the first while loop 
2. assume it's not CLOSE
3. we then read from the network stream at maximum `n` bytes. Assume at this point a second websocket frame has arrived so `buffer will look something like 
```
PROTOCOL LINE
PAYLOAD
<WebSocketFrameHeader Bytes> PROTOCOL LINE
PAYLOAD
```
Note that the first websocket frame header has already been stripped by the initial while loop
4. in `filterPayload` we'll return the bytes read based on the payload length of the first websocket frame header
5. NatsConnectionReader  processes the first message but never the second because the number of bytes read returned by WebSocketInputStream.read will be the number of bytes of the first websocket frames payload
6. NatsConnectionReader calls `read` on WebSocketInputStream again. At this point the we have skipped over the second Frame that was put into the buffer in the initieal `read`

Pertinent Code references: 

https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/support/WebsocketInputStream.java#L57
https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/impl/NatsConnectionReader.java#L122

### Fix

In WebsocketInputStream we'll have to deal with the possibilities that our network read may contain multiple websocket frames, correctly deal with all involved headers and return the sum of the payload lengths as the number of bytes read. I'll get started on a fix but it may take a while because I'm not very familiar with the internals of this codebase. Any help would be appriciated.  

Currently I think the easiest fix is to adjust the length of the network read to be bounded by the websocket frame headers payload length. Any subsequent frames would be left on the network buffer and picked up by the next read.

However there's 2 points I'm unsure about that approach to a fix:

1. What if the passed length `n` is smaller than the payload length i.e. it doesn't fit into the buffer?
2. How to deal with Frame Fragmentation? Or does the nats server never fragment frames?

#### OS/Container environment:

OS: NixOS 23.05.20230430.da45bf6 (Stoat) x86_64
Nats-Server: alpine3.17 docker image
nats java client: 2.16.10

**Comment by GrafBlutwurst** [comment]
@scottf Sorry to ping you out of the blue here, but I was wondering if you knew when this fix is going to be released? It's a bit of a blocker for us and we'd like to know if we have to release a intermediate version inhouse to build against.

**Comment by scottf** [comment]
Probably in a couple weeks. Can you use snapshot for now? 2.16.12-SNAPSHOT is available. See here for instructions for using snapshots with gradle and maven https://github.com/nats-io/nats.java/blob/main/README.md#using-gradle
