### ISSUE TITLE
Update JwtUtils to support complete "nats" Data Structure.

### ISSUE THREAD

**Issue by scottf** [nats-io/nats.java#903]

**Comment by netesh3** [comment]
As we discussed over the slack channel, please consider authenticating NATS using user JWT, let me add snippet.
` private static Connection connectNatsUsingJwt(String userJwt) throws IOException, InterruptedException, GeneralSecurityException {
        Options options = new Options.Builder()
                .server("nats://localhost:4222")
                .authHandler(new AuthHandler() {
                    @Override
                    public byte[] sign(byte[] nonce) {
                        return new byte[0];
                    }

                    @Override
                    public char[] getID() {
                        return new char[0];
                    }

                    @Override
                    public char[] getJWT() {
                        return userJwt.toCharArray();
                    }
                }).build();

        Connection nc = Nats.connect(options);
        System.out.println("Connected to NATS server");
        return nc;
    }`
