### ISSUE TITLE
Add a hook into the Statistics interface to observe counter changes

### ISSUE THREAD

**Issue by johnlcox** [nats-io/nats.java#960]
### What motivated this proposal?

I want to track connection statistics in Prometheus. Since the `Statistics` class only provides counter values, I can't directly increment a prometheus counter from the statistics object.

### What is the proposed change?

Provide a way on the `Statistics` interface to register an observer for each of the counters that can observe the counts being incremented directly. This way a Prometheus counter could be incremented in addition to the NATS in memory counters.

### Who benefits from this change?

Anyone that wants to track connection metrics in an external monitoring system.

### What alternatives have you evaluated?

I'm considering using a prometheus gauge and just documenting very clearly that it's actually a counter.

**Comment by scottf** [comment]
@johnlcox You could implement the ConnectionListener and add it to your connections either via the connection Options or directly to the connection. You get an event every time there is a connection status change.

```
Options options = new Options.Builder()
    ...
    .connectionListener(custsomConnectionListener)
    build();
```

https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/ConnectionListener.java
https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/Options.java#L1325
https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/Connection.java#L413

**Comment by johnlcox** [comment]
Would ConnectionListener be able to provide in/out bytes and in/out msg counts? Those are the metrics I'm looking to get from `Statistics`. We've already got a connection listener implementation tracking the events, but I'm not seeing a way to get the byte/msg counts.

**Comment by johnlcox** [comment]
Yeah. I can take a crack at it. 

Is pulling up `NatsStatistics` an interface and pulling down the current implementation preferable compared to having a `StatisticsListener` that could be set on options that gets hooked into the existing `NatsStatistics` class that could either be null or have a no-op implementation if one is not provided on options?

**Comment by johnlcox** [comment]
Is there a reason why a bunch of the methods on `NatsStatistics` don't have corresponding getters on `Statistics`? For example, `incrementPingCount`, and `incrementRequestsSent`, among others.

**Comment by johnlcox** [comment]
Prometheus metrics use `double` for counters while `NatsStatistics` uses `long` so the listener may be the easier approach. Otherwise implementations that need to implement the getters methods of the interface may need to do funky casts from double/long when different metrics tracking counts things with different types.

**Comment by scottf** [comment]
* I believe the Statistics is just a read only view. It looks like it should be updated to be able to read everything that is available in NatsStatistics.
* There should be a new Interface that is something like StatisticsGatherer that NatsStatistics implements
* Any method signature in Statistics cannot be changed. But new methods of any signature can be added, including a double version of an existing one that returns long. Under the covers you can do anything you like with any variable that is not public. So if you switch from AtomicLong to DoubleAccumulator / DoubleAdder you will have to make sure you do the casts for implementing existing Statistics signatures and public signatures. You can change NatsStatistics methods that are package or private scoped, but will have to address where they are used.

**Comment by johnlcox** [comment]
I've got a good chunk written, but I'm having trouble getting the junit tests to run. Do you have any quidance on running those? I'm on a mac, and it appears to be starting the server for tests but connecting is failing with a `TimeoutException` in `NatsConnection.tryToConnect`.

**Comment by scottf** [comment]
@johnlcox Find me on the public Nats slack and you can DM me.
